// Code generated by ent, DO NOT EDIT.

package mediamodeldefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldModelID, v))
}

// MediaType applies equality check predicate on the "media_type" field. It's identical to MediaTypeEQ.
func MediaType(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldMediaType, v))
}

// BillingUnit applies equality check predicate on the "billing_unit" field. It's identical to BillingUnitEQ.
func BillingUnit(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldBillingUnit, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContainsFold(FieldModelID, v))
}

// MediaTypeEQ applies the EQ predicate on the "media_type" field.
func MediaTypeEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldMediaType, v))
}

// MediaTypeNEQ applies the NEQ predicate on the "media_type" field.
func MediaTypeNEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldMediaType, v))
}

// MediaTypeIn applies the In predicate on the "media_type" field.
func MediaTypeIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldMediaType, vs...))
}

// MediaTypeNotIn applies the NotIn predicate on the "media_type" field.
func MediaTypeNotIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldMediaType, vs...))
}

// MediaTypeGT applies the GT predicate on the "media_type" field.
func MediaTypeGT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldMediaType, v))
}

// MediaTypeGTE applies the GTE predicate on the "media_type" field.
func MediaTypeGTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldMediaType, v))
}

// MediaTypeLT applies the LT predicate on the "media_type" field.
func MediaTypeLT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldMediaType, v))
}

// MediaTypeLTE applies the LTE predicate on the "media_type" field.
func MediaTypeLTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldMediaType, v))
}

// MediaTypeContains applies the Contains predicate on the "media_type" field.
func MediaTypeContains(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContains(FieldMediaType, v))
}

// MediaTypeHasPrefix applies the HasPrefix predicate on the "media_type" field.
func MediaTypeHasPrefix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasPrefix(FieldMediaType, v))
}

// MediaTypeHasSuffix applies the HasSuffix predicate on the "media_type" field.
func MediaTypeHasSuffix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasSuffix(FieldMediaType, v))
}

// MediaTypeEqualFold applies the EqualFold predicate on the "media_type" field.
func MediaTypeEqualFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEqualFold(FieldMediaType, v))
}

// MediaTypeContainsFold applies the ContainsFold predicate on the "media_type" field.
func MediaTypeContainsFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContainsFold(FieldMediaType, v))
}

// BillingUnitEQ applies the EQ predicate on the "billing_unit" field.
func BillingUnitEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldBillingUnit, v))
}

// BillingUnitNEQ applies the NEQ predicate on the "billing_unit" field.
func BillingUnitNEQ(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldBillingUnit, v))
}

// BillingUnitIn applies the In predicate on the "billing_unit" field.
func BillingUnitIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldIn(FieldBillingUnit, vs...))
}

// BillingUnitNotIn applies the NotIn predicate on the "billing_unit" field.
func BillingUnitNotIn(vs ...string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNotIn(FieldBillingUnit, vs...))
}

// BillingUnitGT applies the GT predicate on the "billing_unit" field.
func BillingUnitGT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGT(FieldBillingUnit, v))
}

// BillingUnitGTE applies the GTE predicate on the "billing_unit" field.
func BillingUnitGTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldGTE(FieldBillingUnit, v))
}

// BillingUnitLT applies the LT predicate on the "billing_unit" field.
func BillingUnitLT(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLT(FieldBillingUnit, v))
}

// BillingUnitLTE applies the LTE predicate on the "billing_unit" field.
func BillingUnitLTE(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldLTE(FieldBillingUnit, v))
}

// BillingUnitContains applies the Contains predicate on the "billing_unit" field.
func BillingUnitContains(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContains(FieldBillingUnit, v))
}

// BillingUnitHasPrefix applies the HasPrefix predicate on the "billing_unit" field.
func BillingUnitHasPrefix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasPrefix(FieldBillingUnit, v))
}

// BillingUnitHasSuffix applies the HasSuffix predicate on the "billing_unit" field.
func BillingUnitHasSuffix(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldHasSuffix(FieldBillingUnit, v))
}

// BillingUnitEqualFold applies the EqualFold predicate on the "billing_unit" field.
func BillingUnitEqualFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEqualFold(FieldBillingUnit, v))
}

// BillingUnitContainsFold applies the ContainsFold predicate on the "billing_unit" field.
func BillingUnitContainsFold(v string) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldContainsFold(FieldBillingUnit, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaModelDefinition) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaModelDefinition) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaModelDefinition) predicate.MediaModelDefinition {
	return predicate.MediaModelDefinition(sql.NotPredicates(p))
}
