// Code generated by ent, DO NOT EDIT.

package mediamodelalias

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestedModelID applies equality check predicate on the "requested_model_id" field. It's identical to RequestedModelIDEQ.
func RequestedModelID(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldRequestedModelID, v))
}

// ModelDefinitionID applies equality check predicate on the "model_definition_id" field. It's identical to ModelDefinitionIDEQ.
func ModelDefinitionID(v int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldModelDefinitionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestedModelIDEQ applies the EQ predicate on the "requested_model_id" field.
func RequestedModelIDEQ(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldRequestedModelID, v))
}

// RequestedModelIDNEQ applies the NEQ predicate on the "requested_model_id" field.
func RequestedModelIDNEQ(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNEQ(FieldRequestedModelID, v))
}

// RequestedModelIDIn applies the In predicate on the "requested_model_id" field.
func RequestedModelIDIn(vs ...string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldIn(FieldRequestedModelID, vs...))
}

// RequestedModelIDNotIn applies the NotIn predicate on the "requested_model_id" field.
func RequestedModelIDNotIn(vs ...string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNotIn(FieldRequestedModelID, vs...))
}

// RequestedModelIDGT applies the GT predicate on the "requested_model_id" field.
func RequestedModelIDGT(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGT(FieldRequestedModelID, v))
}

// RequestedModelIDGTE applies the GTE predicate on the "requested_model_id" field.
func RequestedModelIDGTE(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldGTE(FieldRequestedModelID, v))
}

// RequestedModelIDLT applies the LT predicate on the "requested_model_id" field.
func RequestedModelIDLT(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLT(FieldRequestedModelID, v))
}

// RequestedModelIDLTE applies the LTE predicate on the "requested_model_id" field.
func RequestedModelIDLTE(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldLTE(FieldRequestedModelID, v))
}

// RequestedModelIDContains applies the Contains predicate on the "requested_model_id" field.
func RequestedModelIDContains(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldContains(FieldRequestedModelID, v))
}

// RequestedModelIDHasPrefix applies the HasPrefix predicate on the "requested_model_id" field.
func RequestedModelIDHasPrefix(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldHasPrefix(FieldRequestedModelID, v))
}

// RequestedModelIDHasSuffix applies the HasSuffix predicate on the "requested_model_id" field.
func RequestedModelIDHasSuffix(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldHasSuffix(FieldRequestedModelID, v))
}

// RequestedModelIDEqualFold applies the EqualFold predicate on the "requested_model_id" field.
func RequestedModelIDEqualFold(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEqualFold(FieldRequestedModelID, v))
}

// RequestedModelIDContainsFold applies the ContainsFold predicate on the "requested_model_id" field.
func RequestedModelIDContainsFold(v string) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldContainsFold(FieldRequestedModelID, v))
}

// ModelDefinitionIDEQ applies the EQ predicate on the "model_definition_id" field.
func ModelDefinitionIDEQ(v int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldEQ(FieldModelDefinitionID, v))
}

// ModelDefinitionIDNEQ applies the NEQ predicate on the "model_definition_id" field.
func ModelDefinitionIDNEQ(v int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNEQ(FieldModelDefinitionID, v))
}

// ModelDefinitionIDIn applies the In predicate on the "model_definition_id" field.
func ModelDefinitionIDIn(vs ...int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldIn(FieldModelDefinitionID, vs...))
}

// ModelDefinitionIDNotIn applies the NotIn predicate on the "model_definition_id" field.
func ModelDefinitionIDNotIn(vs ...int64) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.FieldNotIn(FieldModelDefinitionID, vs...))
}

// HasModelDefinition applies the HasEdge predicate on the "model_definition" edge.
func HasModelDefinition() predicate.MediaModelAlias {
	return predicate.MediaModelAlias(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ModelDefinitionTable, ModelDefinitionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelDefinitionWith applies the HasEdge predicate on the "model_definition" edge with a given conditions (other predicates).
func HasModelDefinitionWith(preds ...predicate.MediaModelDefinition) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(func(s *sql.Selector) {
		step := newModelDefinitionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaModelAlias) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaModelAlias) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaModelAlias) predicate.MediaModelAlias {
	return predicate.MediaModelAlias(sql.NotPredicates(p))
}
