// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/giftbalancerecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GiftBalanceRecordUpdate is the builder for updating GiftBalanceRecord entities.
type GiftBalanceRecordUpdate struct {
	config
	hooks    []Hook
	mutation *GiftBalanceRecordMutation
}

// Where appends a list predicates to the GiftBalanceRecordUpdate builder.
func (_u *GiftBalanceRecordUpdate) Where(ps ...predicate.GiftBalanceRecord) *GiftBalanceRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GiftBalanceRecordUpdate) SetUserID(v int64) *GiftBalanceRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableUserID(v *int64) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GiftBalanceRecordUpdate) AddUserID(v int64) *GiftBalanceRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *GiftBalanceRecordUpdate) SetAmount(v float64) *GiftBalanceRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableAmount(v *float64) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *GiftBalanceRecordUpdate) AddAmount(v float64) *GiftBalanceRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *GiftBalanceRecordUpdate) SetRemaining(v float64) *GiftBalanceRecordUpdate {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableRemaining(v *float64) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *GiftBalanceRecordUpdate) AddRemaining(v float64) *GiftBalanceRecordUpdate {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *GiftBalanceRecordUpdate) SetSource(v string) *GiftBalanceRecordUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableSource(v *string) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRefID sets the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdate) SetSourceRefID(v int64) *GiftBalanceRecordUpdate {
	_u.mutation.ResetSourceRefID()
	_u.mutation.SetSourceRefID(v)
	return _u
}

// SetNillableSourceRefID sets the "source_ref_id" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableSourceRefID(v *int64) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetSourceRefID(*v)
	}
	return _u
}

// AddSourceRefID adds value to the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdate) AddSourceRefID(v int64) *GiftBalanceRecordUpdate {
	_u.mutation.AddSourceRefID(v)
	return _u
}

// ClearSourceRefID clears the value of the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdate) ClearSourceRefID() *GiftBalanceRecordUpdate {
	_u.mutation.ClearSourceRefID()
	return _u
}

// SetNote sets the "note" field.
func (_u *GiftBalanceRecordUpdate) SetNote(v string) *GiftBalanceRecordUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableNote(v *string) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GiftBalanceRecordUpdate) SetExpiresAt(v time.Time) *GiftBalanceRecordUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdate) SetNillableExpiresAt(v *time.Time) *GiftBalanceRecordUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GiftBalanceRecordUpdate) ClearExpiresAt() *GiftBalanceRecordUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GiftBalanceRecordUpdate) SetUpdatedAt(v time.Time) *GiftBalanceRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GiftBalanceRecordMutation object of the builder.
func (_u *GiftBalanceRecordUpdate) Mutation() *GiftBalanceRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GiftBalanceRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GiftBalanceRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GiftBalanceRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GiftBalanceRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GiftBalanceRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := giftbalancerecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GiftBalanceRecordUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := giftbalancerecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "GiftBalanceRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *GiftBalanceRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(giftbalancerecord.Table, giftbalancerecord.Columns, sqlgraph.NewFieldSpec(giftbalancerecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(giftbalancerecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(giftbalancerecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(giftbalancerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(giftbalancerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(giftbalancerecord.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(giftbalancerecord.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(giftbalancerecord.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRefID(); ok {
		_spec.SetField(giftbalancerecord.FieldSourceRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceRefID(); ok {
		_spec.AddField(giftbalancerecord.FieldSourceRefID, field.TypeInt64, value)
	}
	if _u.mutation.SourceRefIDCleared() {
		_spec.ClearField(giftbalancerecord.FieldSourceRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(giftbalancerecord.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(giftbalancerecord.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(giftbalancerecord.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(giftbalancerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{giftbalancerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GiftBalanceRecordUpdateOne is the builder for updating a single GiftBalanceRecord entity.
type GiftBalanceRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GiftBalanceRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *GiftBalanceRecordUpdateOne) SetUserID(v int64) *GiftBalanceRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableUserID(v *int64) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GiftBalanceRecordUpdateOne) AddUserID(v int64) *GiftBalanceRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *GiftBalanceRecordUpdateOne) SetAmount(v float64) *GiftBalanceRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableAmount(v *float64) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *GiftBalanceRecordUpdateOne) AddAmount(v float64) *GiftBalanceRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *GiftBalanceRecordUpdateOne) SetRemaining(v float64) *GiftBalanceRecordUpdateOne {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableRemaining(v *float64) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *GiftBalanceRecordUpdateOne) AddRemaining(v float64) *GiftBalanceRecordUpdateOne {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *GiftBalanceRecordUpdateOne) SetSource(v string) *GiftBalanceRecordUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableSource(v *string) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRefID sets the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdateOne) SetSourceRefID(v int64) *GiftBalanceRecordUpdateOne {
	_u.mutation.ResetSourceRefID()
	_u.mutation.SetSourceRefID(v)
	return _u
}

// SetNillableSourceRefID sets the "source_ref_id" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableSourceRefID(v *int64) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetSourceRefID(*v)
	}
	return _u
}

// AddSourceRefID adds value to the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdateOne) AddSourceRefID(v int64) *GiftBalanceRecordUpdateOne {
	_u.mutation.AddSourceRefID(v)
	return _u
}

// ClearSourceRefID clears the value of the "source_ref_id" field.
func (_u *GiftBalanceRecordUpdateOne) ClearSourceRefID() *GiftBalanceRecordUpdateOne {
	_u.mutation.ClearSourceRefID()
	return _u
}

// SetNote sets the "note" field.
func (_u *GiftBalanceRecordUpdateOne) SetNote(v string) *GiftBalanceRecordUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableNote(v *string) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GiftBalanceRecordUpdateOne) SetExpiresAt(v time.Time) *GiftBalanceRecordUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GiftBalanceRecordUpdateOne) SetNillableExpiresAt(v *time.Time) *GiftBalanceRecordUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *GiftBalanceRecordUpdateOne) ClearExpiresAt() *GiftBalanceRecordUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GiftBalanceRecordUpdateOne) SetUpdatedAt(v time.Time) *GiftBalanceRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GiftBalanceRecordMutation object of the builder.
func (_u *GiftBalanceRecordUpdateOne) Mutation() *GiftBalanceRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the GiftBalanceRecordUpdate builder.
func (_u *GiftBalanceRecordUpdateOne) Where(ps ...predicate.GiftBalanceRecord) *GiftBalanceRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GiftBalanceRecordUpdateOne) Select(field string, fields ...string) *GiftBalanceRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GiftBalanceRecord entity.
func (_u *GiftBalanceRecordUpdateOne) Save(ctx context.Context) (*GiftBalanceRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GiftBalanceRecordUpdateOne) SaveX(ctx context.Context) *GiftBalanceRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GiftBalanceRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GiftBalanceRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GiftBalanceRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := giftbalancerecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GiftBalanceRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := giftbalancerecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "GiftBalanceRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *GiftBalanceRecordUpdateOne) sqlSave(ctx context.Context) (_node *GiftBalanceRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(giftbalancerecord.Table, giftbalancerecord.Columns, sqlgraph.NewFieldSpec(giftbalancerecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GiftBalanceRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, giftbalancerecord.FieldID)
		for _, f := range fields {
			if !giftbalancerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != giftbalancerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(giftbalancerecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(giftbalancerecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(giftbalancerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(giftbalancerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(giftbalancerecord.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(giftbalancerecord.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(giftbalancerecord.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRefID(); ok {
		_spec.SetField(giftbalancerecord.FieldSourceRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceRefID(); ok {
		_spec.AddField(giftbalancerecord.FieldSourceRefID, field.TypeInt64, value)
	}
	if _u.mutation.SourceRefIDCleared() {
		_spec.ClearField(giftbalancerecord.FieldSourceRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(giftbalancerecord.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(giftbalancerecord.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(giftbalancerecord.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(giftbalancerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GiftBalanceRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{giftbalancerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
