// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouproutesnapshot"
)

// GroupRouteSnapshotCreate is the builder for creating a GroupRouteSnapshot entity.
type GroupRouteSnapshotCreate struct {
	config
	mutation *GroupRouteSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupRouteSnapshotCreate) SetCreatedAt(v time.Time) *GroupRouteSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupRouteSnapshotCreate) SetNillableCreatedAt(v *time.Time) *GroupRouteSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupRouteSnapshotCreate) SetUpdatedAt(v time.Time) *GroupRouteSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupRouteSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *GroupRouteSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupRouteSnapshotCreate) SetGroupID(v int64) *GroupRouteSnapshotCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *GroupRouteSnapshotCreate) SetVersion(v int64) *GroupRouteSnapshotCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GroupRouteSnapshotCreate) SetStatus(v string) *GroupRouteSnapshotCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GroupRouteSnapshotCreate) SetNillableStatus(v *string) *GroupRouteSnapshotCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetManifest sets the "manifest" field.
func (_c *GroupRouteSnapshotCreate) SetManifest(v map[string]interface{}) *GroupRouteSnapshotCreate {
	_c.mutation.SetManifest(v)
	return _c
}

// SetShadowDiff sets the "shadow_diff" field.
func (_c *GroupRouteSnapshotCreate) SetShadowDiff(v map[string]interface{}) *GroupRouteSnapshotCreate {
	_c.mutation.SetShadowDiff(v)
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *GroupRouteSnapshotCreate) SetApprovedBy(v int64) *GroupRouteSnapshotCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *GroupRouteSnapshotCreate) SetNillableApprovedBy(v *int64) *GroupRouteSnapshotCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *GroupRouteSnapshotCreate) SetApprovedAt(v time.Time) *GroupRouteSnapshotCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *GroupRouteSnapshotCreate) SetNillableApprovedAt(v *time.Time) *GroupRouteSnapshotCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// Mutation returns the GroupRouteSnapshotMutation object of the builder.
func (_c *GroupRouteSnapshotCreate) Mutation() *GroupRouteSnapshotMutation {
	return _c.mutation
}

// Save creates the GroupRouteSnapshot in the database.
func (_c *GroupRouteSnapshotCreate) Save(ctx context.Context) (*GroupRouteSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupRouteSnapshotCreate) SaveX(ctx context.Context) *GroupRouteSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupRouteSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupRouteSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupRouteSnapshotCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grouproutesnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grouproutesnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := grouproutesnapshot.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Manifest(); !ok {
		v := grouproutesnapshot.DefaultManifest
		_c.mutation.SetManifest(v)
	}
	if _, ok := _c.mutation.ShadowDiff(); !ok {
		v := grouproutesnapshot.DefaultShadowDiff
		_c.mutation.SetShadowDiff(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupRouteSnapshotCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupRouteSnapshot.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupRouteSnapshot.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupRouteSnapshot.group_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "GroupRouteSnapshot.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := grouproutesnapshot.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "GroupRouteSnapshot.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GroupRouteSnapshot.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := grouproutesnapshot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupRouteSnapshot.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Manifest(); !ok {
		return &ValidationError{Name: "manifest", err: errors.New(`ent: missing required field "GroupRouteSnapshot.manifest"`)}
	}
	if _, ok := _c.mutation.ShadowDiff(); !ok {
		return &ValidationError{Name: "shadow_diff", err: errors.New(`ent: missing required field "GroupRouteSnapshot.shadow_diff"`)}
	}
	return nil
}

func (_c *GroupRouteSnapshotCreate) sqlSave(ctx context.Context) (*GroupRouteSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupRouteSnapshotCreate) createSpec() (*GroupRouteSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupRouteSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grouproutesnapshot.Table, sqlgraph.NewFieldSpec(grouproutesnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grouproutesnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grouproutesnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(grouproutesnapshot.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(grouproutesnapshot.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(grouproutesnapshot.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Manifest(); ok {
		_spec.SetField(grouproutesnapshot.FieldManifest, field.TypeJSON, value)
		_node.Manifest = value
	}
	if value, ok := _c.mutation.ShadowDiff(); ok {
		_spec.SetField(grouproutesnapshot.FieldShadowDiff, field.TypeJSON, value)
		_node.ShadowDiff = value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(grouproutesnapshot.FieldApprovedBy, field.TypeInt64, value)
		_node.ApprovedBy = &value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(grouproutesnapshot.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupRouteSnapshot.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupRouteSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupRouteSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *GroupRouteSnapshotUpsertOne {
	_c.conflict = opts
	return &GroupRouteSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupRouteSnapshotCreate) OnConflictColumns(columns ...string) *GroupRouteSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupRouteSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// GroupRouteSnapshotUpsertOne is the builder for "upsert"-ing
	//  one GroupRouteSnapshot node.
	GroupRouteSnapshotUpsertOne struct {
		create *GroupRouteSnapshotCreate
	}

	// GroupRouteSnapshotUpsert is the "OnConflict" setter.
	GroupRouteSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupRouteSnapshotUpsert) SetUpdatedAt(v time.Time) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateUpdatedAt() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *GroupRouteSnapshotUpsert) SetStatus(v string) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateStatus() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldStatus)
	return u
}

// SetManifest sets the "manifest" field.
func (u *GroupRouteSnapshotUpsert) SetManifest(v map[string]interface{}) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldManifest, v)
	return u
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateManifest() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldManifest)
	return u
}

// SetShadowDiff sets the "shadow_diff" field.
func (u *GroupRouteSnapshotUpsert) SetShadowDiff(v map[string]interface{}) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldShadowDiff, v)
	return u
}

// UpdateShadowDiff sets the "shadow_diff" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateShadowDiff() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldShadowDiff)
	return u
}

// SetApprovedBy sets the "approved_by" field.
func (u *GroupRouteSnapshotUpsert) SetApprovedBy(v int64) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldApprovedBy, v)
	return u
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateApprovedBy() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldApprovedBy)
	return u
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *GroupRouteSnapshotUpsert) AddApprovedBy(v int64) *GroupRouteSnapshotUpsert {
	u.Add(grouproutesnapshot.FieldApprovedBy, v)
	return u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *GroupRouteSnapshotUpsert) ClearApprovedBy() *GroupRouteSnapshotUpsert {
	u.SetNull(grouproutesnapshot.FieldApprovedBy)
	return u
}

// SetApprovedAt sets the "approved_at" field.
func (u *GroupRouteSnapshotUpsert) SetApprovedAt(v time.Time) *GroupRouteSnapshotUpsert {
	u.Set(grouproutesnapshot.FieldApprovedAt, v)
	return u
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsert) UpdateApprovedAt() *GroupRouteSnapshotUpsert {
	u.SetExcluded(grouproutesnapshot.FieldApprovedAt)
	return u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *GroupRouteSnapshotUpsert) ClearApprovedAt() *GroupRouteSnapshotUpsert {
	u.SetNull(grouproutesnapshot.FieldApprovedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupRouteSnapshotUpsertOne) UpdateNewValues() *GroupRouteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grouproutesnapshot.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(grouproutesnapshot.FieldGroupID)
		}
		if _, exists := u.create.mutation.Version(); exists {
			s.SetIgnore(grouproutesnapshot.FieldVersion)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupRouteSnapshotUpsertOne) Ignore() *GroupRouteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupRouteSnapshotUpsertOne) DoNothing() *GroupRouteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupRouteSnapshotCreate.OnConflict
// documentation for more info.
func (u *GroupRouteSnapshotUpsertOne) Update(set func(*GroupRouteSnapshotUpsert)) *GroupRouteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupRouteSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupRouteSnapshotUpsertOne) SetUpdatedAt(v time.Time) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateUpdatedAt() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *GroupRouteSnapshotUpsertOne) SetStatus(v string) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateStatus() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetManifest sets the "manifest" field.
func (u *GroupRouteSnapshotUpsertOne) SetManifest(v map[string]interface{}) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateManifest() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateManifest()
	})
}

// SetShadowDiff sets the "shadow_diff" field.
func (u *GroupRouteSnapshotUpsertOne) SetShadowDiff(v map[string]interface{}) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetShadowDiff(v)
	})
}

// UpdateShadowDiff sets the "shadow_diff" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateShadowDiff() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateShadowDiff()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *GroupRouteSnapshotUpsertOne) SetApprovedBy(v int64) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetApprovedBy(v)
	})
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *GroupRouteSnapshotUpsertOne) AddApprovedBy(v int64) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.AddApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateApprovedBy() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *GroupRouteSnapshotUpsertOne) ClearApprovedBy() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.ClearApprovedBy()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *GroupRouteSnapshotUpsertOne) SetApprovedAt(v time.Time) *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertOne) UpdateApprovedAt() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *GroupRouteSnapshotUpsertOne) ClearApprovedAt() *GroupRouteSnapshotUpsertOne {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.ClearApprovedAt()
	})
}

// Exec executes the query.
func (u *GroupRouteSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupRouteSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupRouteSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupRouteSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupRouteSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupRouteSnapshotCreateBulk is the builder for creating many GroupRouteSnapshot entities in bulk.
type GroupRouteSnapshotCreateBulk struct {
	config
	err      error
	builders []*GroupRouteSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupRouteSnapshot entities in the database.
func (_c *GroupRouteSnapshotCreateBulk) Save(ctx context.Context) ([]*GroupRouteSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupRouteSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupRouteSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupRouteSnapshotCreateBulk) SaveX(ctx context.Context) []*GroupRouteSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupRouteSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupRouteSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupRouteSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupRouteSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupRouteSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupRouteSnapshotUpsertBulk {
	_c.conflict = opts
	return &GroupRouteSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupRouteSnapshotCreateBulk) OnConflictColumns(columns ...string) *GroupRouteSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupRouteSnapshotUpsertBulk{
		create: _c,
	}
}

// GroupRouteSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupRouteSnapshot nodes.
type GroupRouteSnapshotUpsertBulk struct {
	create *GroupRouteSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupRouteSnapshotUpsertBulk) UpdateNewValues() *GroupRouteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grouproutesnapshot.FieldCreatedAt)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(grouproutesnapshot.FieldGroupID)
			}
			if _, exists := b.mutation.Version(); exists {
				s.SetIgnore(grouproutesnapshot.FieldVersion)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupRouteSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupRouteSnapshotUpsertBulk) Ignore() *GroupRouteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupRouteSnapshotUpsertBulk) DoNothing() *GroupRouteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupRouteSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *GroupRouteSnapshotUpsertBulk) Update(set func(*GroupRouteSnapshotUpsert)) *GroupRouteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupRouteSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupRouteSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateUpdatedAt() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *GroupRouteSnapshotUpsertBulk) SetStatus(v string) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateStatus() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetManifest sets the "manifest" field.
func (u *GroupRouteSnapshotUpsertBulk) SetManifest(v map[string]interface{}) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateManifest() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateManifest()
	})
}

// SetShadowDiff sets the "shadow_diff" field.
func (u *GroupRouteSnapshotUpsertBulk) SetShadowDiff(v map[string]interface{}) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetShadowDiff(v)
	})
}

// UpdateShadowDiff sets the "shadow_diff" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateShadowDiff() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateShadowDiff()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *GroupRouteSnapshotUpsertBulk) SetApprovedBy(v int64) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetApprovedBy(v)
	})
}

// AddApprovedBy adds v to the "approved_by" field.
func (u *GroupRouteSnapshotUpsertBulk) AddApprovedBy(v int64) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.AddApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateApprovedBy() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *GroupRouteSnapshotUpsertBulk) ClearApprovedBy() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.ClearApprovedBy()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *GroupRouteSnapshotUpsertBulk) SetApprovedAt(v time.Time) *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *GroupRouteSnapshotUpsertBulk) UpdateApprovedAt() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *GroupRouteSnapshotUpsertBulk) ClearApprovedAt() *GroupRouteSnapshotUpsertBulk {
	return u.Update(func(s *GroupRouteSnapshotUpsert) {
		s.ClearApprovedAt()
	})
}

// Exec executes the query.
func (u *GroupRouteSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupRouteSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupRouteSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupRouteSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
