// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediamodeldefinition"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaModelDefinitionUpdate is the builder for updating MediaModelDefinition entities.
type MediaModelDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *MediaModelDefinitionMutation
}

// Where appends a list predicates to the MediaModelDefinitionUpdate builder.
func (_u *MediaModelDefinitionUpdate) Where(ps ...predicate.MediaModelDefinition) *MediaModelDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaModelDefinitionUpdate) SetUpdatedAt(v time.Time) *MediaModelDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *MediaModelDefinitionUpdate) SetModelID(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableModelID(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *MediaModelDefinitionUpdate) SetVendor(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableVendor(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaModelDefinitionUpdate) SetMediaType(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableMediaType(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetOperations sets the "operations" field.
func (_u *MediaModelDefinitionUpdate) SetOperations(v []string) *MediaModelDefinitionUpdate {
	_u.mutation.SetOperations(v)
	return _u
}

// AppendOperations appends value to the "operations" field.
func (_u *MediaModelDefinitionUpdate) AppendOperations(v []string) *MediaModelDefinitionUpdate {
	_u.mutation.AppendOperations(v)
	return _u
}

// SetConstraints sets the "constraints" field.
func (_u *MediaModelDefinitionUpdate) SetConstraints(v json.RawMessage) *MediaModelDefinitionUpdate {
	_u.mutation.SetConstraints(v)
	return _u
}

// AppendConstraints appends value to the "constraints" field.
func (_u *MediaModelDefinitionUpdate) AppendConstraints(v json.RawMessage) *MediaModelDefinitionUpdate {
	_u.mutation.AppendConstraints(v)
	return _u
}

// SetBillingUnit sets the "billing_unit" field.
func (_u *MediaModelDefinitionUpdate) SetBillingUnit(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetBillingUnit(v)
	return _u
}

// SetNillableBillingUnit sets the "billing_unit" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableBillingUnit(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetBillingUnit(*v)
	}
	return _u
}

// SetDefaultAdapter sets the "default_adapter" field.
func (_u *MediaModelDefinitionUpdate) SetDefaultAdapter(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetDefaultAdapter(v)
	return _u
}

// SetNillableDefaultAdapter sets the "default_adapter" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableDefaultAdapter(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetDefaultAdapter(*v)
	}
	return _u
}

// SetDefaultAsyncMode sets the "default_async_mode" field.
func (_u *MediaModelDefinitionUpdate) SetDefaultAsyncMode(v string) *MediaModelDefinitionUpdate {
	_u.mutation.SetDefaultAsyncMode(v)
	return _u
}

// SetNillableDefaultAsyncMode sets the "default_async_mode" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableDefaultAsyncMode(v *string) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetDefaultAsyncMode(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaModelDefinitionUpdate) SetEnabled(v bool) *MediaModelDefinitionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdate) SetNillableEnabled(v *bool) *MediaModelDefinitionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the MediaModelDefinitionMutation object of the builder.
func (_u *MediaModelDefinitionUpdate) Mutation() *MediaModelDefinitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaModelDefinitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaModelDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaModelDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaModelDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaModelDefinitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediamodeldefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaModelDefinitionUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := mediamodeldefinition.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := mediamodeldefinition.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := mediamodeldefinition.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingUnit(); ok {
		if err := mediamodeldefinition.BillingUnitValidator(v); err != nil {
			return &ValidationError{Name: "billing_unit", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.billing_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultAdapter(); ok {
		if err := mediamodeldefinition.DefaultAdapterValidator(v); err != nil {
			return &ValidationError{Name: "default_adapter", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.default_adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultAsyncMode(); ok {
		if err := mediamodeldefinition.DefaultAsyncModeValidator(v); err != nil {
			return &ValidationError{Name: "default_async_mode", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.default_async_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaModelDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediamodeldefinition.Table, mediamodeldefinition.Columns, sqlgraph.NewFieldSpec(mediamodeldefinition.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediamodeldefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(mediamodeldefinition.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(mediamodeldefinition.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediamodeldefinition.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operations(); ok {
		_spec.SetField(mediamodeldefinition.FieldOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediamodeldefinition.FieldOperations, value)
		})
	}
	if value, ok := _u.mutation.Constraints(); ok {
		_spec.SetField(mediamodeldefinition.FieldConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediamodeldefinition.FieldConstraints, value)
		})
	}
	if value, ok := _u.mutation.BillingUnit(); ok {
		_spec.SetField(mediamodeldefinition.FieldBillingUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultAdapter(); ok {
		_spec.SetField(mediamodeldefinition.FieldDefaultAdapter, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultAsyncMode(); ok {
		_spec.SetField(mediamodeldefinition.FieldDefaultAsyncMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediamodeldefinition.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediamodeldefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaModelDefinitionUpdateOne is the builder for updating a single MediaModelDefinition entity.
type MediaModelDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaModelDefinitionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaModelDefinitionUpdateOne) SetUpdatedAt(v time.Time) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *MediaModelDefinitionUpdateOne) SetModelID(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableModelID(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *MediaModelDefinitionUpdateOne) SetVendor(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableVendor(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaModelDefinitionUpdateOne) SetMediaType(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableMediaType(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetOperations sets the "operations" field.
func (_u *MediaModelDefinitionUpdateOne) SetOperations(v []string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetOperations(v)
	return _u
}

// AppendOperations appends value to the "operations" field.
func (_u *MediaModelDefinitionUpdateOne) AppendOperations(v []string) *MediaModelDefinitionUpdateOne {
	_u.mutation.AppendOperations(v)
	return _u
}

// SetConstraints sets the "constraints" field.
func (_u *MediaModelDefinitionUpdateOne) SetConstraints(v json.RawMessage) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetConstraints(v)
	return _u
}

// AppendConstraints appends value to the "constraints" field.
func (_u *MediaModelDefinitionUpdateOne) AppendConstraints(v json.RawMessage) *MediaModelDefinitionUpdateOne {
	_u.mutation.AppendConstraints(v)
	return _u
}

// SetBillingUnit sets the "billing_unit" field.
func (_u *MediaModelDefinitionUpdateOne) SetBillingUnit(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetBillingUnit(v)
	return _u
}

// SetNillableBillingUnit sets the "billing_unit" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableBillingUnit(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetBillingUnit(*v)
	}
	return _u
}

// SetDefaultAdapter sets the "default_adapter" field.
func (_u *MediaModelDefinitionUpdateOne) SetDefaultAdapter(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetDefaultAdapter(v)
	return _u
}

// SetNillableDefaultAdapter sets the "default_adapter" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableDefaultAdapter(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetDefaultAdapter(*v)
	}
	return _u
}

// SetDefaultAsyncMode sets the "default_async_mode" field.
func (_u *MediaModelDefinitionUpdateOne) SetDefaultAsyncMode(v string) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetDefaultAsyncMode(v)
	return _u
}

// SetNillableDefaultAsyncMode sets the "default_async_mode" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableDefaultAsyncMode(v *string) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetDefaultAsyncMode(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MediaModelDefinitionUpdateOne) SetEnabled(v bool) *MediaModelDefinitionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MediaModelDefinitionUpdateOne) SetNillableEnabled(v *bool) *MediaModelDefinitionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the MediaModelDefinitionMutation object of the builder.
func (_u *MediaModelDefinitionUpdateOne) Mutation() *MediaModelDefinitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaModelDefinitionUpdate builder.
func (_u *MediaModelDefinitionUpdateOne) Where(ps ...predicate.MediaModelDefinition) *MediaModelDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaModelDefinitionUpdateOne) Select(field string, fields ...string) *MediaModelDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaModelDefinition entity.
func (_u *MediaModelDefinitionUpdateOne) Save(ctx context.Context) (*MediaModelDefinition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaModelDefinitionUpdateOne) SaveX(ctx context.Context) *MediaModelDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaModelDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaModelDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaModelDefinitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediamodeldefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaModelDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := mediamodeldefinition.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := mediamodeldefinition.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := mediamodeldefinition.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingUnit(); ok {
		if err := mediamodeldefinition.BillingUnitValidator(v); err != nil {
			return &ValidationError{Name: "billing_unit", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.billing_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultAdapter(); ok {
		if err := mediamodeldefinition.DefaultAdapterValidator(v); err != nil {
			return &ValidationError{Name: "default_adapter", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.default_adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultAsyncMode(); ok {
		if err := mediamodeldefinition.DefaultAsyncModeValidator(v); err != nil {
			return &ValidationError{Name: "default_async_mode", err: fmt.Errorf(`ent: validator failed for field "MediaModelDefinition.default_async_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaModelDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *MediaModelDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediamodeldefinition.Table, mediamodeldefinition.Columns, sqlgraph.NewFieldSpec(mediamodeldefinition.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaModelDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediamodeldefinition.FieldID)
		for _, f := range fields {
			if !mediamodeldefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediamodeldefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediamodeldefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(mediamodeldefinition.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(mediamodeldefinition.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediamodeldefinition.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operations(); ok {
		_spec.SetField(mediamodeldefinition.FieldOperations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOperations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediamodeldefinition.FieldOperations, value)
		})
	}
	if value, ok := _u.mutation.Constraints(); ok {
		_spec.SetField(mediamodeldefinition.FieldConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediamodeldefinition.FieldConstraints, value)
		})
	}
	if value, ok := _u.mutation.BillingUnit(); ok {
		_spec.SetField(mediamodeldefinition.FieldBillingUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultAdapter(); ok {
		_spec.SetField(mediamodeldefinition.FieldDefaultAdapter, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultAsyncMode(); ok {
		_spec.SetField(mediamodeldefinition.FieldDefaultAsyncMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mediamodeldefinition.FieldEnabled, field.TypeBool, value)
	}
	_node = &MediaModelDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediamodeldefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
