// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediamodelalias"
	"github.com/Wei-Shaw/sub2api/ent/mediamodeldefinition"
)

// MediaModelAliasCreate is the builder for creating a MediaModelAlias entity.
type MediaModelAliasCreate struct {
	config
	mutation *MediaModelAliasMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaModelAliasCreate) SetCreatedAt(v time.Time) *MediaModelAliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaModelAliasCreate) SetNillableCreatedAt(v *time.Time) *MediaModelAliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaModelAliasCreate) SetUpdatedAt(v time.Time) *MediaModelAliasCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaModelAliasCreate) SetNillableUpdatedAt(v *time.Time) *MediaModelAliasCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRequestedModelID sets the "requested_model_id" field.
func (_c *MediaModelAliasCreate) SetRequestedModelID(v string) *MediaModelAliasCreate {
	_c.mutation.SetRequestedModelID(v)
	return _c
}

// SetModelDefinitionID sets the "model_definition_id" field.
func (_c *MediaModelAliasCreate) SetModelDefinitionID(v int64) *MediaModelAliasCreate {
	_c.mutation.SetModelDefinitionID(v)
	return _c
}

// SetModelDefinition sets the "model_definition" edge to the MediaModelDefinition entity.
func (_c *MediaModelAliasCreate) SetModelDefinition(v *MediaModelDefinition) *MediaModelAliasCreate {
	return _c.SetModelDefinitionID(v.ID)
}

// Mutation returns the MediaModelAliasMutation object of the builder.
func (_c *MediaModelAliasCreate) Mutation() *MediaModelAliasMutation {
	return _c.mutation
}

// Save creates the MediaModelAlias in the database.
func (_c *MediaModelAliasCreate) Save(ctx context.Context) (*MediaModelAlias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaModelAliasCreate) SaveX(ctx context.Context) *MediaModelAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaModelAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaModelAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaModelAliasCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediamodelalias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediamodelalias.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaModelAliasCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaModelAlias.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MediaModelAlias.updated_at"`)}
	}
	if _, ok := _c.mutation.RequestedModelID(); !ok {
		return &ValidationError{Name: "requested_model_id", err: errors.New(`ent: missing required field "MediaModelAlias.requested_model_id"`)}
	}
	if v, ok := _c.mutation.RequestedModelID(); ok {
		if err := mediamodelalias.RequestedModelIDValidator(v); err != nil {
			return &ValidationError{Name: "requested_model_id", err: fmt.Errorf(`ent: validator failed for field "MediaModelAlias.requested_model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelDefinitionID(); !ok {
		return &ValidationError{Name: "model_definition_id", err: errors.New(`ent: missing required field "MediaModelAlias.model_definition_id"`)}
	}
	if len(_c.mutation.ModelDefinitionIDs()) == 0 {
		return &ValidationError{Name: "model_definition", err: errors.New(`ent: missing required edge "MediaModelAlias.model_definition"`)}
	}
	return nil
}

func (_c *MediaModelAliasCreate) sqlSave(ctx context.Context) (*MediaModelAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaModelAliasCreate) createSpec() (*MediaModelAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaModelAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediamodelalias.Table, sqlgraph.NewFieldSpec(mediamodelalias.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediamodelalias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediamodelalias.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RequestedModelID(); ok {
		_spec.SetField(mediamodelalias.FieldRequestedModelID, field.TypeString, value)
		_node.RequestedModelID = value
	}
	if nodes := _c.mutation.ModelDefinitionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mediamodelalias.ModelDefinitionTable,
			Columns: []string{mediamodelalias.ModelDefinitionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediamodeldefinition.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelDefinitionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaModelAlias.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaModelAliasUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaModelAliasCreate) OnConflict(opts ...sql.ConflictOption) *MediaModelAliasUpsertOne {
	_c.conflict = opts
	return &MediaModelAliasUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaModelAliasCreate) OnConflictColumns(columns ...string) *MediaModelAliasUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaModelAliasUpsertOne{
		create: _c,
	}
}

type (
	// MediaModelAliasUpsertOne is the builder for "upsert"-ing
	//  one MediaModelAlias node.
	MediaModelAliasUpsertOne struct {
		create *MediaModelAliasCreate
	}

	// MediaModelAliasUpsert is the "OnConflict" setter.
	MediaModelAliasUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaModelAliasUpsert) SetUpdatedAt(v time.Time) *MediaModelAliasUpsert {
	u.Set(mediamodelalias.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaModelAliasUpsert) UpdateUpdatedAt() *MediaModelAliasUpsert {
	u.SetExcluded(mediamodelalias.FieldUpdatedAt)
	return u
}

// SetRequestedModelID sets the "requested_model_id" field.
func (u *MediaModelAliasUpsert) SetRequestedModelID(v string) *MediaModelAliasUpsert {
	u.Set(mediamodelalias.FieldRequestedModelID, v)
	return u
}

// UpdateRequestedModelID sets the "requested_model_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsert) UpdateRequestedModelID() *MediaModelAliasUpsert {
	u.SetExcluded(mediamodelalias.FieldRequestedModelID)
	return u
}

// SetModelDefinitionID sets the "model_definition_id" field.
func (u *MediaModelAliasUpsert) SetModelDefinitionID(v int64) *MediaModelAliasUpsert {
	u.Set(mediamodelalias.FieldModelDefinitionID, v)
	return u
}

// UpdateModelDefinitionID sets the "model_definition_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsert) UpdateModelDefinitionID() *MediaModelAliasUpsert {
	u.SetExcluded(mediamodelalias.FieldModelDefinitionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaModelAliasUpsertOne) UpdateNewValues() *MediaModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mediamodelalias.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaModelAliasUpsertOne) Ignore() *MediaModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaModelAliasUpsertOne) DoNothing() *MediaModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaModelAliasCreate.OnConflict
// documentation for more info.
func (u *MediaModelAliasUpsertOne) Update(set func(*MediaModelAliasUpsert)) *MediaModelAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaModelAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaModelAliasUpsertOne) SetUpdatedAt(v time.Time) *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaModelAliasUpsertOne) UpdateUpdatedAt() *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestedModelID sets the "requested_model_id" field.
func (u *MediaModelAliasUpsertOne) SetRequestedModelID(v string) *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetRequestedModelID(v)
	})
}

// UpdateRequestedModelID sets the "requested_model_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsertOne) UpdateRequestedModelID() *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateRequestedModelID()
	})
}

// SetModelDefinitionID sets the "model_definition_id" field.
func (u *MediaModelAliasUpsertOne) SetModelDefinitionID(v int64) *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetModelDefinitionID(v)
	})
}

// UpdateModelDefinitionID sets the "model_definition_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsertOne) UpdateModelDefinitionID() *MediaModelAliasUpsertOne {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateModelDefinitionID()
	})
}

// Exec executes the query.
func (u *MediaModelAliasUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaModelAliasCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaModelAliasUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaModelAliasUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaModelAliasUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaModelAliasCreateBulk is the builder for creating many MediaModelAlias entities in bulk.
type MediaModelAliasCreateBulk struct {
	config
	err      error
	builders []*MediaModelAliasCreate
	conflict []sql.ConflictOption
}

// Save creates the MediaModelAlias entities in the database.
func (_c *MediaModelAliasCreateBulk) Save(ctx context.Context) ([]*MediaModelAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaModelAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaModelAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaModelAliasCreateBulk) SaveX(ctx context.Context) []*MediaModelAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaModelAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaModelAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaModelAlias.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaModelAliasUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaModelAliasCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaModelAliasUpsertBulk {
	_c.conflict = opts
	return &MediaModelAliasUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaModelAliasCreateBulk) OnConflictColumns(columns ...string) *MediaModelAliasUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaModelAliasUpsertBulk{
		create: _c,
	}
}

// MediaModelAliasUpsertBulk is the builder for "upsert"-ing
// a bulk of MediaModelAlias nodes.
type MediaModelAliasUpsertBulk struct {
	create *MediaModelAliasCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaModelAliasUpsertBulk) UpdateNewValues() *MediaModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mediamodelalias.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaModelAlias.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaModelAliasUpsertBulk) Ignore() *MediaModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaModelAliasUpsertBulk) DoNothing() *MediaModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaModelAliasCreateBulk.OnConflict
// documentation for more info.
func (u *MediaModelAliasUpsertBulk) Update(set func(*MediaModelAliasUpsert)) *MediaModelAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaModelAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaModelAliasUpsertBulk) SetUpdatedAt(v time.Time) *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaModelAliasUpsertBulk) UpdateUpdatedAt() *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestedModelID sets the "requested_model_id" field.
func (u *MediaModelAliasUpsertBulk) SetRequestedModelID(v string) *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetRequestedModelID(v)
	})
}

// UpdateRequestedModelID sets the "requested_model_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsertBulk) UpdateRequestedModelID() *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateRequestedModelID()
	})
}

// SetModelDefinitionID sets the "model_definition_id" field.
func (u *MediaModelAliasUpsertBulk) SetModelDefinitionID(v int64) *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.SetModelDefinitionID(v)
	})
}

// UpdateModelDefinitionID sets the "model_definition_id" field to the value that was provided on create.
func (u *MediaModelAliasUpsertBulk) UpdateModelDefinitionID() *MediaModelAliasUpsertBulk {
	return u.Update(func(s *MediaModelAliasUpsert) {
		s.UpdateModelDefinitionID()
	})
}

// Exec executes the query.
func (u *MediaModelAliasUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MediaModelAliasCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaModelAliasCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaModelAliasUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
