// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promotion"
	"github.com/Wei-Shaw/sub2api/ent/promotionusage"
)

// PromotionUsage is the model entity for the PromotionUsage schema.
type PromotionUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 活动 ID
	PromotionID int64 `json:"promotion_id,omitempty"`
	// 订阅活动记录 plan；充值活动为 NULL
	PlanID *int64 `json:"plan_id,omitempty"`
	// 使用用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// payment_orders.id
	OrderID int64 `json:"order_id,omitempty"`
	// 减少金额（订阅按减额/折扣后差值；充值 reduce_pay 节省）
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	// 充值 bonus_credit 模式赠送金额
	BonusAmount float64 `json:"bonus_amount,omitempty"`
	// 使用时间
	UsedAt time.Time `json:"used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromotionUsageQuery when eager-loading is set.
	Edges        PromotionUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PromotionUsageEdges holds the relations/edges for other nodes in the graph.
type PromotionUsageEdges struct {
	// Promotion holds the value of the promotion edge.
	Promotion *Promotion `json:"promotion,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PromotionOrErr returns the Promotion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PromotionUsageEdges) PromotionOrErr() (*Promotion, error) {
	if e.Promotion != nil {
		return e.Promotion, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: promotion.Label}
	}
	return nil, &NotLoadedError{edge: "promotion"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionusage.FieldDiscountAmount, promotionusage.FieldBonusAmount:
			values[i] = new(sql.NullFloat64)
		case promotionusage.FieldID, promotionusage.FieldPromotionID, promotionusage.FieldPlanID, promotionusage.FieldUserID, promotionusage.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case promotionusage.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionUsage fields.
func (_m *PromotionUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promotionusage.FieldPromotionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field promotion_id", values[i])
			} else if value.Valid {
				_m.PromotionID = value.Int64
			}
		case promotionusage.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case promotionusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case promotionusage.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case promotionusage.FieldDiscountAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_amount", values[i])
			} else if value.Valid {
				_m.DiscountAmount = value.Float64
			}
		case promotionusage.FieldBonusAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_amount", values[i])
			} else if value.Valid {
				_m.BonusAmount = value.Float64
			}
		case promotionusage.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionUsage.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPromotion queries the "promotion" edge of the PromotionUsage entity.
func (_m *PromotionUsage) QueryPromotion() *PromotionQuery {
	return NewPromotionUsageClient(_m.config).QueryPromotion(_m)
}

// Update returns a builder for updating this PromotionUsage.
// Note that you need to call PromotionUsage.Unwrap() before calling this method if this PromotionUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionUsage) Update() *PromotionUsageUpdateOne {
	return NewPromotionUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionUsage) Unwrap() *PromotionUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionUsage) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("promotion_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromotionID))
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("discount_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountAmount))
	builder.WriteString(", ")
	builder.WriteString("bonus_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusAmount))
	builder.WriteString(", ")
	builder.WriteString("used_at=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionUsages is a parsable slice of PromotionUsage.
type PromotionUsages []*PromotionUsage
