// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promotion"
	"github.com/Wei-Shaw/sub2api/ent/promotionplanrule"
)

// PromotionPlanRuleCreate is the builder for creating a PromotionPlanRule entity.
type PromotionPlanRuleCreate struct {
	config
	mutation *PromotionPlanRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPromotionID sets the "promotion_id" field.
func (_c *PromotionPlanRuleCreate) SetPromotionID(v int64) *PromotionPlanRuleCreate {
	_c.mutation.SetPromotionID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PromotionPlanRuleCreate) SetPlanID(v int64) *PromotionPlanRuleCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetDiscountMode sets the "discount_mode" field.
func (_c *PromotionPlanRuleCreate) SetDiscountMode(v string) *PromotionPlanRuleCreate {
	_c.mutation.SetDiscountMode(v)
	return _c
}

// SetDiscountRate sets the "discount_rate" field.
func (_c *PromotionPlanRuleCreate) SetDiscountRate(v float64) *PromotionPlanRuleCreate {
	_c.mutation.SetDiscountRate(v)
	return _c
}

// SetNillableDiscountRate sets the "discount_rate" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableDiscountRate(v *float64) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetDiscountRate(*v)
	}
	return _c
}

// SetDiscountAmount sets the "discount_amount" field.
func (_c *PromotionPlanRuleCreate) SetDiscountAmount(v float64) *PromotionPlanRuleCreate {
	_c.mutation.SetDiscountAmount(v)
	return _c
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableDiscountAmount(v *float64) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetDiscountAmount(*v)
	}
	return _c
}

// SetMinPriceFloor sets the "min_price_floor" field.
func (_c *PromotionPlanRuleCreate) SetMinPriceFloor(v float64) *PromotionPlanRuleCreate {
	_c.mutation.SetMinPriceFloor(v)
	return _c
}

// SetNillableMinPriceFloor sets the "min_price_floor" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableMinPriceFloor(v *float64) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetMinPriceFloor(*v)
	}
	return _c
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (_c *PromotionPlanRuleCreate) SetMaxUsesPerUser(v int) *PromotionPlanRuleCreate {
	_c.mutation.SetMaxUsesPerUser(v)
	return _c
}

// SetNillableMaxUsesPerUser sets the "max_uses_per_user" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableMaxUsesPerUser(v *int) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetMaxUsesPerUser(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionPlanRuleCreate) SetCreatedAt(v time.Time) *PromotionPlanRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableCreatedAt(v *time.Time) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromotionPlanRuleCreate) SetUpdatedAt(v time.Time) *PromotionPlanRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromotionPlanRuleCreate) SetNillableUpdatedAt(v *time.Time) *PromotionPlanRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPromotion sets the "promotion" edge to the Promotion entity.
func (_c *PromotionPlanRuleCreate) SetPromotion(v *Promotion) *PromotionPlanRuleCreate {
	return _c.SetPromotionID(v.ID)
}

// Mutation returns the PromotionPlanRuleMutation object of the builder.
func (_c *PromotionPlanRuleCreate) Mutation() *PromotionPlanRuleMutation {
	return _c.mutation
}

// Save creates the PromotionPlanRule in the database.
func (_c *PromotionPlanRuleCreate) Save(ctx context.Context) (*PromotionPlanRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionPlanRuleCreate) SaveX(ctx context.Context) *PromotionPlanRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionPlanRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionPlanRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionPlanRuleCreate) defaults() {
	if _, ok := _c.mutation.MinPriceFloor(); !ok {
		v := promotionplanrule.DefaultMinPriceFloor
		_c.mutation.SetMinPriceFloor(v)
	}
	if _, ok := _c.mutation.MaxUsesPerUser(); !ok {
		v := promotionplanrule.DefaultMaxUsesPerUser
		_c.mutation.SetMaxUsesPerUser(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionplanrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promotionplanrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionPlanRuleCreate) check() error {
	if _, ok := _c.mutation.PromotionID(); !ok {
		return &ValidationError{Name: "promotion_id", err: errors.New(`ent: missing required field "PromotionPlanRule.promotion_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "PromotionPlanRule.plan_id"`)}
	}
	if _, ok := _c.mutation.DiscountMode(); !ok {
		return &ValidationError{Name: "discount_mode", err: errors.New(`ent: missing required field "PromotionPlanRule.discount_mode"`)}
	}
	if v, ok := _c.mutation.DiscountMode(); ok {
		if err := promotionplanrule.DiscountModeValidator(v); err != nil {
			return &ValidationError{Name: "discount_mode", err: fmt.Errorf(`ent: validator failed for field "PromotionPlanRule.discount_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinPriceFloor(); !ok {
		return &ValidationError{Name: "min_price_floor", err: errors.New(`ent: missing required field "PromotionPlanRule.min_price_floor"`)}
	}
	if _, ok := _c.mutation.MaxUsesPerUser(); !ok {
		return &ValidationError{Name: "max_uses_per_user", err: errors.New(`ent: missing required field "PromotionPlanRule.max_uses_per_user"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionPlanRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromotionPlanRule.updated_at"`)}
	}
	if len(_c.mutation.PromotionIDs()) == 0 {
		return &ValidationError{Name: "promotion", err: errors.New(`ent: missing required edge "PromotionPlanRule.promotion"`)}
	}
	return nil
}

func (_c *PromotionPlanRuleCreate) sqlSave(ctx context.Context) (*PromotionPlanRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionPlanRuleCreate) createSpec() (*PromotionPlanRule, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionPlanRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionplanrule.Table, sqlgraph.NewFieldSpec(promotionplanrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(promotionplanrule.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.DiscountMode(); ok {
		_spec.SetField(promotionplanrule.FieldDiscountMode, field.TypeString, value)
		_node.DiscountMode = value
	}
	if value, ok := _c.mutation.DiscountRate(); ok {
		_spec.SetField(promotionplanrule.FieldDiscountRate, field.TypeFloat64, value)
		_node.DiscountRate = &value
	}
	if value, ok := _c.mutation.DiscountAmount(); ok {
		_spec.SetField(promotionplanrule.FieldDiscountAmount, field.TypeFloat64, value)
		_node.DiscountAmount = &value
	}
	if value, ok := _c.mutation.MinPriceFloor(); ok {
		_spec.SetField(promotionplanrule.FieldMinPriceFloor, field.TypeFloat64, value)
		_node.MinPriceFloor = value
	}
	if value, ok := _c.mutation.MaxUsesPerUser(); ok {
		_spec.SetField(promotionplanrule.FieldMaxUsesPerUser, field.TypeInt, value)
		_node.MaxUsesPerUser = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionplanrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promotionplanrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PromotionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promotionplanrule.PromotionTable,
			Columns: []string{promotionplanrule.PromotionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promotion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PromotionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionPlanRule.Create().
//		SetPromotionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionPlanRuleUpsert) {
//			SetPromotionID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionPlanRuleCreate) OnConflict(opts ...sql.ConflictOption) *PromotionPlanRuleUpsertOne {
	_c.conflict = opts
	return &PromotionPlanRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionPlanRuleCreate) OnConflictColumns(columns ...string) *PromotionPlanRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionPlanRuleUpsertOne{
		create: _c,
	}
}

type (
	// PromotionPlanRuleUpsertOne is the builder for "upsert"-ing
	//  one PromotionPlanRule node.
	PromotionPlanRuleUpsertOne struct {
		create *PromotionPlanRuleCreate
	}

	// PromotionPlanRuleUpsert is the "OnConflict" setter.
	PromotionPlanRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionPlanRuleUpsert) SetPromotionID(v int64) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldPromotionID, v)
	return u
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdatePromotionID() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldPromotionID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionPlanRuleUpsert) SetPlanID(v int64) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdatePlanID() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionPlanRuleUpsert) AddPlanID(v int64) *PromotionPlanRuleUpsert {
	u.Add(promotionplanrule.FieldPlanID, v)
	return u
}

// SetDiscountMode sets the "discount_mode" field.
func (u *PromotionPlanRuleUpsert) SetDiscountMode(v string) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldDiscountMode, v)
	return u
}

// UpdateDiscountMode sets the "discount_mode" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateDiscountMode() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldDiscountMode)
	return u
}

// SetDiscountRate sets the "discount_rate" field.
func (u *PromotionPlanRuleUpsert) SetDiscountRate(v float64) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldDiscountRate, v)
	return u
}

// UpdateDiscountRate sets the "discount_rate" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateDiscountRate() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldDiscountRate)
	return u
}

// AddDiscountRate adds v to the "discount_rate" field.
func (u *PromotionPlanRuleUpsert) AddDiscountRate(v float64) *PromotionPlanRuleUpsert {
	u.Add(promotionplanrule.FieldDiscountRate, v)
	return u
}

// ClearDiscountRate clears the value of the "discount_rate" field.
func (u *PromotionPlanRuleUpsert) ClearDiscountRate() *PromotionPlanRuleUpsert {
	u.SetNull(promotionplanrule.FieldDiscountRate)
	return u
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PromotionPlanRuleUpsert) SetDiscountAmount(v float64) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldDiscountAmount, v)
	return u
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateDiscountAmount() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldDiscountAmount)
	return u
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PromotionPlanRuleUpsert) AddDiscountAmount(v float64) *PromotionPlanRuleUpsert {
	u.Add(promotionplanrule.FieldDiscountAmount, v)
	return u
}

// ClearDiscountAmount clears the value of the "discount_amount" field.
func (u *PromotionPlanRuleUpsert) ClearDiscountAmount() *PromotionPlanRuleUpsert {
	u.SetNull(promotionplanrule.FieldDiscountAmount)
	return u
}

// SetMinPriceFloor sets the "min_price_floor" field.
func (u *PromotionPlanRuleUpsert) SetMinPriceFloor(v float64) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldMinPriceFloor, v)
	return u
}

// UpdateMinPriceFloor sets the "min_price_floor" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateMinPriceFloor() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldMinPriceFloor)
	return u
}

// AddMinPriceFloor adds v to the "min_price_floor" field.
func (u *PromotionPlanRuleUpsert) AddMinPriceFloor(v float64) *PromotionPlanRuleUpsert {
	u.Add(promotionplanrule.FieldMinPriceFloor, v)
	return u
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsert) SetMaxUsesPerUser(v int) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldMaxUsesPerUser, v)
	return u
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateMaxUsesPerUser() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldMaxUsesPerUser)
	return u
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsert) AddMaxUsesPerUser(v int) *PromotionPlanRuleUpsert {
	u.Add(promotionplanrule.FieldMaxUsesPerUser, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionPlanRuleUpsert) SetUpdatedAt(v time.Time) *PromotionPlanRuleUpsert {
	u.Set(promotionplanrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsert) UpdateUpdatedAt() *PromotionPlanRuleUpsert {
	u.SetExcluded(promotionplanrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionPlanRuleUpsertOne) UpdateNewValues() *PromotionPlanRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionplanrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionPlanRuleUpsertOne) Ignore() *PromotionPlanRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionPlanRuleUpsertOne) DoNothing() *PromotionPlanRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionPlanRuleCreate.OnConflict
// documentation for more info.
func (u *PromotionPlanRuleUpsertOne) Update(set func(*PromotionPlanRuleUpsert)) *PromotionPlanRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionPlanRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionPlanRuleUpsertOne) SetPromotionID(v int64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetPromotionID(v)
	})
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdatePromotionID() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdatePromotionID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionPlanRuleUpsertOne) SetPlanID(v int64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionPlanRuleUpsertOne) AddPlanID(v int64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdatePlanID() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdatePlanID()
	})
}

// SetDiscountMode sets the "discount_mode" field.
func (u *PromotionPlanRuleUpsertOne) SetDiscountMode(v string) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountMode(v)
	})
}

// UpdateDiscountMode sets the "discount_mode" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateDiscountMode() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountMode()
	})
}

// SetDiscountRate sets the "discount_rate" field.
func (u *PromotionPlanRuleUpsertOne) SetDiscountRate(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountRate(v)
	})
}

// AddDiscountRate adds v to the "discount_rate" field.
func (u *PromotionPlanRuleUpsertOne) AddDiscountRate(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddDiscountRate(v)
	})
}

// UpdateDiscountRate sets the "discount_rate" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateDiscountRate() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountRate()
	})
}

// ClearDiscountRate clears the value of the "discount_rate" field.
func (u *PromotionPlanRuleUpsertOne) ClearDiscountRate() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.ClearDiscountRate()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PromotionPlanRuleUpsertOne) SetDiscountAmount(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PromotionPlanRuleUpsertOne) AddDiscountAmount(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateDiscountAmount() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountAmount()
	})
}

// ClearDiscountAmount clears the value of the "discount_amount" field.
func (u *PromotionPlanRuleUpsertOne) ClearDiscountAmount() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.ClearDiscountAmount()
	})
}

// SetMinPriceFloor sets the "min_price_floor" field.
func (u *PromotionPlanRuleUpsertOne) SetMinPriceFloor(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetMinPriceFloor(v)
	})
}

// AddMinPriceFloor adds v to the "min_price_floor" field.
func (u *PromotionPlanRuleUpsertOne) AddMinPriceFloor(v float64) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddMinPriceFloor(v)
	})
}

// UpdateMinPriceFloor sets the "min_price_floor" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateMinPriceFloor() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateMinPriceFloor()
	})
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsertOne) SetMaxUsesPerUser(v int) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetMaxUsesPerUser(v)
	})
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsertOne) AddMaxUsesPerUser(v int) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddMaxUsesPerUser(v)
	})
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateMaxUsesPerUser() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateMaxUsesPerUser()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionPlanRuleUpsertOne) SetUpdatedAt(v time.Time) *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertOne) UpdateUpdatedAt() *PromotionPlanRuleUpsertOne {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionPlanRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionPlanRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionPlanRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionPlanRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionPlanRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionPlanRuleCreateBulk is the builder for creating many PromotionPlanRule entities in bulk.
type PromotionPlanRuleCreateBulk struct {
	config
	err      error
	builders []*PromotionPlanRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionPlanRule entities in the database.
func (_c *PromotionPlanRuleCreateBulk) Save(ctx context.Context) ([]*PromotionPlanRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionPlanRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionPlanRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionPlanRuleCreateBulk) SaveX(ctx context.Context) []*PromotionPlanRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionPlanRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionPlanRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionPlanRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionPlanRuleUpsert) {
//			SetPromotionID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionPlanRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionPlanRuleUpsertBulk {
	_c.conflict = opts
	return &PromotionPlanRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionPlanRuleCreateBulk) OnConflictColumns(columns ...string) *PromotionPlanRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionPlanRuleUpsertBulk{
		create: _c,
	}
}

// PromotionPlanRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionPlanRule nodes.
type PromotionPlanRuleUpsertBulk struct {
	create *PromotionPlanRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromotionPlanRuleUpsertBulk) UpdateNewValues() *PromotionPlanRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionplanrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionPlanRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionPlanRuleUpsertBulk) Ignore() *PromotionPlanRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionPlanRuleUpsertBulk) DoNothing() *PromotionPlanRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionPlanRuleCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionPlanRuleUpsertBulk) Update(set func(*PromotionPlanRuleUpsert)) *PromotionPlanRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionPlanRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionPlanRuleUpsertBulk) SetPromotionID(v int64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetPromotionID(v)
	})
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdatePromotionID() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdatePromotionID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PromotionPlanRuleUpsertBulk) SetPlanID(v int64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *PromotionPlanRuleUpsertBulk) AddPlanID(v int64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdatePlanID() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdatePlanID()
	})
}

// SetDiscountMode sets the "discount_mode" field.
func (u *PromotionPlanRuleUpsertBulk) SetDiscountMode(v string) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountMode(v)
	})
}

// UpdateDiscountMode sets the "discount_mode" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateDiscountMode() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountMode()
	})
}

// SetDiscountRate sets the "discount_rate" field.
func (u *PromotionPlanRuleUpsertBulk) SetDiscountRate(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountRate(v)
	})
}

// AddDiscountRate adds v to the "discount_rate" field.
func (u *PromotionPlanRuleUpsertBulk) AddDiscountRate(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddDiscountRate(v)
	})
}

// UpdateDiscountRate sets the "discount_rate" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateDiscountRate() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountRate()
	})
}

// ClearDiscountRate clears the value of the "discount_rate" field.
func (u *PromotionPlanRuleUpsertBulk) ClearDiscountRate() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.ClearDiscountRate()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PromotionPlanRuleUpsertBulk) SetDiscountAmount(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PromotionPlanRuleUpsertBulk) AddDiscountAmount(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateDiscountAmount() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateDiscountAmount()
	})
}

// ClearDiscountAmount clears the value of the "discount_amount" field.
func (u *PromotionPlanRuleUpsertBulk) ClearDiscountAmount() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.ClearDiscountAmount()
	})
}

// SetMinPriceFloor sets the "min_price_floor" field.
func (u *PromotionPlanRuleUpsertBulk) SetMinPriceFloor(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetMinPriceFloor(v)
	})
}

// AddMinPriceFloor adds v to the "min_price_floor" field.
func (u *PromotionPlanRuleUpsertBulk) AddMinPriceFloor(v float64) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddMinPriceFloor(v)
	})
}

// UpdateMinPriceFloor sets the "min_price_floor" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateMinPriceFloor() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateMinPriceFloor()
	})
}

// SetMaxUsesPerUser sets the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsertBulk) SetMaxUsesPerUser(v int) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetMaxUsesPerUser(v)
	})
}

// AddMaxUsesPerUser adds v to the "max_uses_per_user" field.
func (u *PromotionPlanRuleUpsertBulk) AddMaxUsesPerUser(v int) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.AddMaxUsesPerUser(v)
	})
}

// UpdateMaxUsesPerUser sets the "max_uses_per_user" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateMaxUsesPerUser() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateMaxUsesPerUser()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromotionPlanRuleUpsertBulk) SetUpdatedAt(v time.Time) *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromotionPlanRuleUpsertBulk) UpdateUpdatedAt() *PromotionPlanRuleUpsertBulk {
	return u.Update(func(s *PromotionPlanRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PromotionPlanRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionPlanRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionPlanRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionPlanRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
