// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providermigrationreview"
)

// ProviderMigrationReviewUpdate is the builder for updating ProviderMigrationReview entities.
type ProviderMigrationReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMigrationReviewMutation
}

// Where appends a list predicates to the ProviderMigrationReviewUpdate builder.
func (_u *ProviderMigrationReviewUpdate) Where(ps ...predicate.ProviderMigrationReview) *ProviderMigrationReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderMigrationReviewUpdate) SetUpdatedAt(v time.Time) *ProviderMigrationReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProviderMigrationReviewUpdate) SetGroupID(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableGroupID(v *int64) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ProviderMigrationReviewUpdate) AddGroupID(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ProviderMigrationReviewUpdate) ClearGroupID() *ProviderMigrationReviewUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderMigrationReviewUpdate) SetStatus(v string) *ProviderMigrationReviewUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableStatus(v *string) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ProviderMigrationReviewUpdate) SetReason(v string) *ProviderMigrationReviewUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableReason(v *string) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *ProviderMigrationReviewUpdate) SetEvidence(v map[string]interface{}) *ProviderMigrationReviewUpdate {
	_u.mutation.SetEvidence(v)
	return _u
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (_u *ProviderMigrationReviewUpdate) SetSnapshotVersion(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.ResetSnapshotVersion()
	_u.mutation.SetSnapshotVersion(v)
	return _u
}

// SetNillableSnapshotVersion sets the "snapshot_version" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableSnapshotVersion(v *int64) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetSnapshotVersion(*v)
	}
	return _u
}

// AddSnapshotVersion adds value to the "snapshot_version" field.
func (_u *ProviderMigrationReviewUpdate) AddSnapshotVersion(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.AddSnapshotVersion(v)
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdate) SetReviewedBy(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableReviewedBy(v *int64) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdate) AddReviewedBy(v int64) *ProviderMigrationReviewUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdate) ClearReviewedBy() *ProviderMigrationReviewUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ProviderMigrationReviewUpdate) SetReviewedAt(v time.Time) *ProviderMigrationReviewUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdate) SetNillableReviewedAt(v *time.Time) *ProviderMigrationReviewUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ProviderMigrationReviewUpdate) ClearReviewedAt() *ProviderMigrationReviewUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// Mutation returns the ProviderMigrationReviewMutation object of the builder.
func (_u *ProviderMigrationReviewUpdate) Mutation() *ProviderMigrationReviewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderMigrationReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderMigrationReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderMigrationReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderMigrationReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderMigrationReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providermigrationreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderMigrationReviewUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := providermigrationreview.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationReview.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotVersion(); ok {
		if err := providermigrationreview.SnapshotVersionValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_version", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationReview.snapshot_version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderMigrationReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providermigrationreview.Table, providermigrationreview.Columns, sqlgraph.NewFieldSpec(providermigrationreview.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providermigrationreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(providermigrationreview.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(providermigrationreview.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(providermigrationreview.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providermigrationreview.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(providermigrationreview.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(providermigrationreview.FieldEvidence, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SnapshotVersion(); ok {
		_spec.SetField(providermigrationreview.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotVersion(); ok {
		_spec.AddField(providermigrationreview.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(providermigrationreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(providermigrationreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(providermigrationreview.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(providermigrationreview.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(providermigrationreview.FieldReviewedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providermigrationreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderMigrationReviewUpdateOne is the builder for updating a single ProviderMigrationReview entity.
type ProviderMigrationReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMigrationReviewMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderMigrationReviewUpdateOne) SetUpdatedAt(v time.Time) *ProviderMigrationReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ProviderMigrationReviewUpdateOne) SetGroupID(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableGroupID(v *int64) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ProviderMigrationReviewUpdateOne) AddGroupID(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ProviderMigrationReviewUpdateOne) ClearGroupID() *ProviderMigrationReviewUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderMigrationReviewUpdateOne) SetStatus(v string) *ProviderMigrationReviewUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableStatus(v *string) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ProviderMigrationReviewUpdateOne) SetReason(v string) *ProviderMigrationReviewUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableReason(v *string) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *ProviderMigrationReviewUpdateOne) SetEvidence(v map[string]interface{}) *ProviderMigrationReviewUpdateOne {
	_u.mutation.SetEvidence(v)
	return _u
}

// SetSnapshotVersion sets the "snapshot_version" field.
func (_u *ProviderMigrationReviewUpdateOne) SetSnapshotVersion(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.ResetSnapshotVersion()
	_u.mutation.SetSnapshotVersion(v)
	return _u
}

// SetNillableSnapshotVersion sets the "snapshot_version" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableSnapshotVersion(v *int64) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetSnapshotVersion(*v)
	}
	return _u
}

// AddSnapshotVersion adds value to the "snapshot_version" field.
func (_u *ProviderMigrationReviewUpdateOne) AddSnapshotVersion(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.AddSnapshotVersion(v)
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdateOne) SetReviewedBy(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableReviewedBy(v *int64) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdateOne) AddReviewedBy(v int64) *ProviderMigrationReviewUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *ProviderMigrationReviewUpdateOne) ClearReviewedBy() *ProviderMigrationReviewUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ProviderMigrationReviewUpdateOne) SetReviewedAt(v time.Time) *ProviderMigrationReviewUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ProviderMigrationReviewUpdateOne) SetNillableReviewedAt(v *time.Time) *ProviderMigrationReviewUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ProviderMigrationReviewUpdateOne) ClearReviewedAt() *ProviderMigrationReviewUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// Mutation returns the ProviderMigrationReviewMutation object of the builder.
func (_u *ProviderMigrationReviewUpdateOne) Mutation() *ProviderMigrationReviewMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderMigrationReviewUpdate builder.
func (_u *ProviderMigrationReviewUpdateOne) Where(ps ...predicate.ProviderMigrationReview) *ProviderMigrationReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderMigrationReviewUpdateOne) Select(field string, fields ...string) *ProviderMigrationReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderMigrationReview entity.
func (_u *ProviderMigrationReviewUpdateOne) Save(ctx context.Context) (*ProviderMigrationReview, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderMigrationReviewUpdateOne) SaveX(ctx context.Context) *ProviderMigrationReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderMigrationReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderMigrationReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderMigrationReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providermigrationreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderMigrationReviewUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := providermigrationreview.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationReview.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SnapshotVersion(); ok {
		if err := providermigrationreview.SnapshotVersionValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_version", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationReview.snapshot_version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderMigrationReviewUpdateOne) sqlSave(ctx context.Context) (_node *ProviderMigrationReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providermigrationreview.Table, providermigrationreview.Columns, sqlgraph.NewFieldSpec(providermigrationreview.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderMigrationReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providermigrationreview.FieldID)
		for _, f := range fields {
			if !providermigrationreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providermigrationreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providermigrationreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(providermigrationreview.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(providermigrationreview.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(providermigrationreview.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providermigrationreview.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(providermigrationreview.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(providermigrationreview.FieldEvidence, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SnapshotVersion(); ok {
		_spec.SetField(providermigrationreview.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSnapshotVersion(); ok {
		_spec.AddField(providermigrationreview.FieldSnapshotVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(providermigrationreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(providermigrationreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(providermigrationreview.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(providermigrationreview.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(providermigrationreview.FieldReviewedAt, field.TypeTime)
	}
	_node = &ProviderMigrationReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providermigrationreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
