// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerprotocolendpoint"
)

// ProviderProtocolEndpointUpdate is the builder for updating ProviderProtocolEndpoint entities.
type ProviderProtocolEndpointUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderProtocolEndpointMutation
}

// Where appends a list predicates to the ProviderProtocolEndpointUpdate builder.
func (_u *ProviderProtocolEndpointUpdate) Where(ps ...predicate.ProviderProtocolEndpoint) *ProviderProtocolEndpointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderProtocolEndpointUpdate) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWireProfile sets the "wire_profile" field.
func (_u *ProviderProtocolEndpointUpdate) SetWireProfile(v string) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetWireProfile(v)
	return _u
}

// SetNillableWireProfile sets the "wire_profile" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillableWireProfile(v *string) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetWireProfile(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ProviderProtocolEndpointUpdate) SetBaseURL(v string) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillableBaseURL(v *string) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *ProviderProtocolEndpointUpdate) ClearBaseURL() *ProviderProtocolEndpointUpdate {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetPath sets the "path" field.
func (_u *ProviderProtocolEndpointUpdate) SetPath(v string) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillablePath(v *string) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetAuthType sets the "auth_type" field.
func (_u *ProviderProtocolEndpointUpdate) SetAuthType(v string) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetAuthType(v)
	return _u
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillableAuthType(v *string) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetAuthType(*v)
	}
	return _u
}

// ClearAuthType clears the value of the "auth_type" field.
func (_u *ProviderProtocolEndpointUpdate) ClearAuthType() *ProviderProtocolEndpointUpdate {
	_u.mutation.ClearAuthType()
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *ProviderProtocolEndpointUpdate) SetHeaders(v map[string]string) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProviderProtocolEndpointUpdate) SetEnabled(v bool) *ProviderProtocolEndpointUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillableEnabled(v *bool) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderProtocolEndpointUpdate) SetVersion(v int64) *ProviderProtocolEndpointUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdate) SetNillableVersion(v *int64) *ProviderProtocolEndpointUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderProtocolEndpointUpdate) AddVersion(v int64) *ProviderProtocolEndpointUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the ProviderProtocolEndpointMutation object of the builder.
func (_u *ProviderProtocolEndpointUpdate) Mutation() *ProviderProtocolEndpointMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderProtocolEndpointUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderProtocolEndpointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderProtocolEndpointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderProtocolEndpointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderProtocolEndpointUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerprotocolendpoint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderProtocolEndpointUpdate) check() error {
	if v, ok := _u.mutation.WireProfile(); ok {
		if err := providerprotocolendpoint.WireProfileValidator(v); err != nil {
			return &ValidationError{Name: "wire_profile", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.wire_profile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := providerprotocolendpoint.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := providerprotocolendpoint.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthType(); ok {
		if err := providerprotocolendpoint.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.auth_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerprotocolendpoint.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderProtocolEndpointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerprotocolendpoint.Table, providerprotocolendpoint.Columns, sqlgraph.NewFieldSpec(providerprotocolendpoint.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerprotocolendpoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WireProfile(); ok {
		_spec.SetField(providerprotocolendpoint.FieldWireProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(providerprotocolendpoint.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(providerprotocolendpoint.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(providerprotocolendpoint.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthType(); ok {
		_spec.SetField(providerprotocolendpoint.FieldAuthType, field.TypeString, value)
	}
	if _u.mutation.AuthTypeCleared() {
		_spec.ClearField(providerprotocolendpoint.FieldAuthType, field.TypeString)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(providerprotocolendpoint.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(providerprotocolendpoint.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerprotocolendpoint.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerprotocolendpoint.FieldVersion, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerprotocolendpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderProtocolEndpointUpdateOne is the builder for updating a single ProviderProtocolEndpoint entity.
type ProviderProtocolEndpointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderProtocolEndpointMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWireProfile sets the "wire_profile" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetWireProfile(v string) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetWireProfile(v)
	return _u
}

// SetNillableWireProfile sets the "wire_profile" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillableWireProfile(v *string) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetWireProfile(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetBaseURL(v string) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillableBaseURL(v *string) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *ProviderProtocolEndpointUpdateOne) ClearBaseURL() *ProviderProtocolEndpointUpdateOne {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetPath sets the "path" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetPath(v string) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillablePath(v *string) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetAuthType sets the "auth_type" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetAuthType(v string) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetAuthType(v)
	return _u
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillableAuthType(v *string) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetAuthType(*v)
	}
	return _u
}

// ClearAuthType clears the value of the "auth_type" field.
func (_u *ProviderProtocolEndpointUpdateOne) ClearAuthType() *ProviderProtocolEndpointUpdateOne {
	_u.mutation.ClearAuthType()
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetHeaders(v map[string]string) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetEnabled(v bool) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillableEnabled(v *bool) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderProtocolEndpointUpdateOne) SetVersion(v int64) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderProtocolEndpointUpdateOne) SetNillableVersion(v *int64) *ProviderProtocolEndpointUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderProtocolEndpointUpdateOne) AddVersion(v int64) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the ProviderProtocolEndpointMutation object of the builder.
func (_u *ProviderProtocolEndpointUpdateOne) Mutation() *ProviderProtocolEndpointMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderProtocolEndpointUpdate builder.
func (_u *ProviderProtocolEndpointUpdateOne) Where(ps ...predicate.ProviderProtocolEndpoint) *ProviderProtocolEndpointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderProtocolEndpointUpdateOne) Select(field string, fields ...string) *ProviderProtocolEndpointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderProtocolEndpoint entity.
func (_u *ProviderProtocolEndpointUpdateOne) Save(ctx context.Context) (*ProviderProtocolEndpoint, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderProtocolEndpointUpdateOne) SaveX(ctx context.Context) *ProviderProtocolEndpoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderProtocolEndpointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderProtocolEndpointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderProtocolEndpointUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerprotocolendpoint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderProtocolEndpointUpdateOne) check() error {
	if v, ok := _u.mutation.WireProfile(); ok {
		if err := providerprotocolendpoint.WireProfileValidator(v); err != nil {
			return &ValidationError{Name: "wire_profile", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.wire_profile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := providerprotocolendpoint.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := providerprotocolendpoint.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthType(); ok {
		if err := providerprotocolendpoint.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.auth_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerprotocolendpoint.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderProtocolEndpointUpdateOne) sqlSave(ctx context.Context) (_node *ProviderProtocolEndpoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerprotocolendpoint.Table, providerprotocolendpoint.Columns, sqlgraph.NewFieldSpec(providerprotocolendpoint.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderProtocolEndpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerprotocolendpoint.FieldID)
		for _, f := range fields {
			if !providerprotocolendpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerprotocolendpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerprotocolendpoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WireProfile(); ok {
		_spec.SetField(providerprotocolendpoint.FieldWireProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(providerprotocolendpoint.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(providerprotocolendpoint.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(providerprotocolendpoint.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthType(); ok {
		_spec.SetField(providerprotocolendpoint.FieldAuthType, field.TypeString, value)
	}
	if _u.mutation.AuthTypeCleared() {
		_spec.ClearField(providerprotocolendpoint.FieldAuthType, field.TypeString)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(providerprotocolendpoint.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(providerprotocolendpoint.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerprotocolendpoint.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerprotocolendpoint.FieldVersion, field.TypeInt64, value)
	}
	_node = &ProviderProtocolEndpoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerprotocolendpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
