// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providermigrationreview"
)

// ProviderMigrationReview is the model entity for the ProviderMigrationReview schema.
type ProviderMigrationReview struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Evidence holds the value of the "evidence" field.
	Evidence map[string]interface{} `json:"evidence,omitempty"`
	// SnapshotVersion holds the value of the "snapshot_version" field.
	SnapshotVersion int64 `json:"snapshot_version,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy *int64 `json:"reviewed_by,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt   *time.Time `json:"reviewed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderMigrationReview) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providermigrationreview.FieldEvidence:
			values[i] = new([]byte)
		case providermigrationreview.FieldID, providermigrationreview.FieldProviderID, providermigrationreview.FieldGroupID, providermigrationreview.FieldSnapshotVersion, providermigrationreview.FieldReviewedBy:
			values[i] = new(sql.NullInt64)
		case providermigrationreview.FieldStatus, providermigrationreview.FieldReason:
			values[i] = new(sql.NullString)
		case providermigrationreview.FieldCreatedAt, providermigrationreview.FieldUpdatedAt, providermigrationreview.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderMigrationReview fields.
func (_m *ProviderMigrationReview) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providermigrationreview.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providermigrationreview.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case providermigrationreview.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case providermigrationreview.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case providermigrationreview.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case providermigrationreview.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case providermigrationreview.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case providermigrationreview.FieldEvidence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field evidence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Evidence); err != nil {
					return fmt.Errorf("unmarshal field evidence: %w", err)
				}
			}
		case providermigrationreview.FieldSnapshotVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_version", values[i])
			} else if value.Valid {
				_m.SnapshotVersion = value.Int64
			}
		case providermigrationreview.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = new(int64)
				*_m.ReviewedBy = value.Int64
			}
		case providermigrationreview.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderMigrationReview.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderMigrationReview) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderMigrationReview.
// Note that you need to call ProviderMigrationReview.Unwrap() before calling this method if this ProviderMigrationReview
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderMigrationReview) Update() *ProviderMigrationReviewUpdateOne {
	return NewProviderMigrationReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderMigrationReview entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderMigrationReview) Unwrap() *ProviderMigrationReview {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderMigrationReview is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderMigrationReview) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderMigrationReview(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("evidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Evidence))
	builder.WriteString(", ")
	builder.WriteString("snapshot_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnapshotVersion))
	builder.WriteString(", ")
	if v := _m.ReviewedBy; v != nil {
		builder.WriteString("reviewed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProviderMigrationReviews is a parsable slice of ProviderMigrationReview.
type ProviderMigrationReviews []*ProviderMigrationReview
