// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerprotocolendpoint"
)

// ProviderProtocolEndpointCreate is the builder for creating a ProviderProtocolEndpoint entity.
type ProviderProtocolEndpointCreate struct {
	config
	mutation *ProviderProtocolEndpointMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderProtocolEndpointCreate) SetCreatedAt(v time.Time) *ProviderProtocolEndpointCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableCreatedAt(v *time.Time) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderProtocolEndpointCreate) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableUpdatedAt(v *time.Time) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *ProviderProtocolEndpointCreate) SetProviderID(v int64) *ProviderProtocolEndpointCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetProtocolFamily sets the "protocol_family" field.
func (_c *ProviderProtocolEndpointCreate) SetProtocolFamily(v string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetProtocolFamily(v)
	return _c
}

// SetWireProfile sets the "wire_profile" field.
func (_c *ProviderProtocolEndpointCreate) SetWireProfile(v string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetWireProfile(v)
	return _c
}

// SetNillableWireProfile sets the "wire_profile" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableWireProfile(v *string) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetWireProfile(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *ProviderProtocolEndpointCreate) SetBaseURL(v string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableBaseURL(v *string) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetBaseURL(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *ProviderProtocolEndpointCreate) SetPath(v string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetAuthType sets the "auth_type" field.
func (_c *ProviderProtocolEndpointCreate) SetAuthType(v string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetAuthType(v)
	return _c
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableAuthType(v *string) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetAuthType(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *ProviderProtocolEndpointCreate) SetHeaders(v map[string]string) *ProviderProtocolEndpointCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ProviderProtocolEndpointCreate) SetEnabled(v bool) *ProviderProtocolEndpointCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableEnabled(v *bool) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProviderProtocolEndpointCreate) SetVersion(v int64) *ProviderProtocolEndpointCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProviderProtocolEndpointCreate) SetNillableVersion(v *int64) *ProviderProtocolEndpointCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// Mutation returns the ProviderProtocolEndpointMutation object of the builder.
func (_c *ProviderProtocolEndpointCreate) Mutation() *ProviderProtocolEndpointMutation {
	return _c.mutation
}

// Save creates the ProviderProtocolEndpoint in the database.
func (_c *ProviderProtocolEndpointCreate) Save(ctx context.Context) (*ProviderProtocolEndpoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderProtocolEndpointCreate) SaveX(ctx context.Context) *ProviderProtocolEndpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderProtocolEndpointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderProtocolEndpointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderProtocolEndpointCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := providerprotocolendpoint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providerprotocolendpoint.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.WireProfile(); !ok {
		v := providerprotocolendpoint.DefaultWireProfile
		_c.mutation.SetWireProfile(v)
	}
	if _, ok := _c.mutation.Headers(); !ok {
		v := providerprotocolendpoint.DefaultHeaders
		_c.mutation.SetHeaders(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := providerprotocolendpoint.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := providerprotocolendpoint.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderProtocolEndpointCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.updated_at"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.provider_id"`)}
	}
	if _, ok := _c.mutation.ProtocolFamily(); !ok {
		return &ValidationError{Name: "protocol_family", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.protocol_family"`)}
	}
	if v, ok := _c.mutation.ProtocolFamily(); ok {
		if err := providerprotocolendpoint.ProtocolFamilyValidator(v); err != nil {
			return &ValidationError{Name: "protocol_family", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.protocol_family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WireProfile(); !ok {
		return &ValidationError{Name: "wire_profile", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.wire_profile"`)}
	}
	if v, ok := _c.mutation.WireProfile(); ok {
		if err := providerprotocolendpoint.WireProfileValidator(v); err != nil {
			return &ValidationError{Name: "wire_profile", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.wire_profile": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := providerprotocolendpoint.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := providerprotocolendpoint.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthType(); ok {
		if err := providerprotocolendpoint.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.auth_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Headers(); !ok {
		return &ValidationError{Name: "headers", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.headers"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.enabled"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProviderProtocolEndpoint.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := providerprotocolendpoint.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderProtocolEndpoint.version": %w`, err)}
		}
	}
	return nil
}

func (_c *ProviderProtocolEndpointCreate) sqlSave(ctx context.Context) (*ProviderProtocolEndpoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderProtocolEndpointCreate) createSpec() (*ProviderProtocolEndpoint, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderProtocolEndpoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerprotocolendpoint.Table, sqlgraph.NewFieldSpec(providerprotocolendpoint.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(providerprotocolendpoint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providerprotocolendpoint.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(providerprotocolendpoint.FieldProviderID, field.TypeInt64, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.ProtocolFamily(); ok {
		_spec.SetField(providerprotocolendpoint.FieldProtocolFamily, field.TypeString, value)
		_node.ProtocolFamily = value
	}
	if value, ok := _c.mutation.WireProfile(); ok {
		_spec.SetField(providerprotocolendpoint.FieldWireProfile, field.TypeString, value)
		_node.WireProfile = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(providerprotocolendpoint.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = &value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(providerprotocolendpoint.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.AuthType(); ok {
		_spec.SetField(providerprotocolendpoint.FieldAuthType, field.TypeString, value)
		_node.AuthType = &value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(providerprotocolendpoint.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(providerprotocolendpoint.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(providerprotocolendpoint.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderProtocolEndpoint.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderProtocolEndpointUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderProtocolEndpointCreate) OnConflict(opts ...sql.ConflictOption) *ProviderProtocolEndpointUpsertOne {
	_c.conflict = opts
	return &ProviderProtocolEndpointUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderProtocolEndpointCreate) OnConflictColumns(columns ...string) *ProviderProtocolEndpointUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderProtocolEndpointUpsertOne{
		create: _c,
	}
}

type (
	// ProviderProtocolEndpointUpsertOne is the builder for "upsert"-ing
	//  one ProviderProtocolEndpoint node.
	ProviderProtocolEndpointUpsertOne struct {
		create *ProviderProtocolEndpointCreate
	}

	// ProviderProtocolEndpointUpsert is the "OnConflict" setter.
	ProviderProtocolEndpointUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderProtocolEndpointUpsert) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateUpdatedAt() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldUpdatedAt)
	return u
}

// SetWireProfile sets the "wire_profile" field.
func (u *ProviderProtocolEndpointUpsert) SetWireProfile(v string) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldWireProfile, v)
	return u
}

// UpdateWireProfile sets the "wire_profile" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateWireProfile() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldWireProfile)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *ProviderProtocolEndpointUpsert) SetBaseURL(v string) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateBaseURL() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldBaseURL)
	return u
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *ProviderProtocolEndpointUpsert) ClearBaseURL() *ProviderProtocolEndpointUpsert {
	u.SetNull(providerprotocolendpoint.FieldBaseURL)
	return u
}

// SetPath sets the "path" field.
func (u *ProviderProtocolEndpointUpsert) SetPath(v string) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdatePath() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldPath)
	return u
}

// SetAuthType sets the "auth_type" field.
func (u *ProviderProtocolEndpointUpsert) SetAuthType(v string) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldAuthType, v)
	return u
}

// UpdateAuthType sets the "auth_type" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateAuthType() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldAuthType)
	return u
}

// ClearAuthType clears the value of the "auth_type" field.
func (u *ProviderProtocolEndpointUpsert) ClearAuthType() *ProviderProtocolEndpointUpsert {
	u.SetNull(providerprotocolendpoint.FieldAuthType)
	return u
}

// SetHeaders sets the "headers" field.
func (u *ProviderProtocolEndpointUpsert) SetHeaders(v map[string]string) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldHeaders, v)
	return u
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateHeaders() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldHeaders)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ProviderProtocolEndpointUpsert) SetEnabled(v bool) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateEnabled() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldEnabled)
	return u
}

// SetVersion sets the "version" field.
func (u *ProviderProtocolEndpointUpsert) SetVersion(v int64) *ProviderProtocolEndpointUpsert {
	u.Set(providerprotocolendpoint.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsert) UpdateVersion() *ProviderProtocolEndpointUpsert {
	u.SetExcluded(providerprotocolendpoint.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProviderProtocolEndpointUpsert) AddVersion(v int64) *ProviderProtocolEndpointUpsert {
	u.Add(providerprotocolendpoint.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderProtocolEndpointUpsertOne) UpdateNewValues() *ProviderProtocolEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(providerprotocolendpoint.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ProviderID(); exists {
			s.SetIgnore(providerprotocolendpoint.FieldProviderID)
		}
		if _, exists := u.create.mutation.ProtocolFamily(); exists {
			s.SetIgnore(providerprotocolendpoint.FieldProtocolFamily)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderProtocolEndpointUpsertOne) Ignore() *ProviderProtocolEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderProtocolEndpointUpsertOne) DoNothing() *ProviderProtocolEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderProtocolEndpointCreate.OnConflict
// documentation for more info.
func (u *ProviderProtocolEndpointUpsertOne) Update(set func(*ProviderProtocolEndpointUpsert)) *ProviderProtocolEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderProtocolEndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderProtocolEndpointUpsertOne) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateUpdatedAt() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWireProfile sets the "wire_profile" field.
func (u *ProviderProtocolEndpointUpsertOne) SetWireProfile(v string) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetWireProfile(v)
	})
}

// UpdateWireProfile sets the "wire_profile" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateWireProfile() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateWireProfile()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *ProviderProtocolEndpointUpsertOne) SetBaseURL(v string) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateBaseURL() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *ProviderProtocolEndpointUpsertOne) ClearBaseURL() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.ClearBaseURL()
	})
}

// SetPath sets the "path" field.
func (u *ProviderProtocolEndpointUpsertOne) SetPath(v string) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdatePath() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdatePath()
	})
}

// SetAuthType sets the "auth_type" field.
func (u *ProviderProtocolEndpointUpsertOne) SetAuthType(v string) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetAuthType(v)
	})
}

// UpdateAuthType sets the "auth_type" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateAuthType() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateAuthType()
	})
}

// ClearAuthType clears the value of the "auth_type" field.
func (u *ProviderProtocolEndpointUpsertOne) ClearAuthType() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.ClearAuthType()
	})
}

// SetHeaders sets the "headers" field.
func (u *ProviderProtocolEndpointUpsertOne) SetHeaders(v map[string]string) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateHeaders() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateHeaders()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProviderProtocolEndpointUpsertOne) SetEnabled(v bool) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateEnabled() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateEnabled()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderProtocolEndpointUpsertOne) SetVersion(v int64) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderProtocolEndpointUpsertOne) AddVersion(v int64) *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertOne) UpdateVersion() *ProviderProtocolEndpointUpsertOne {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *ProviderProtocolEndpointUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderProtocolEndpointCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderProtocolEndpointUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderProtocolEndpointUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderProtocolEndpointUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderProtocolEndpointCreateBulk is the builder for creating many ProviderProtocolEndpoint entities in bulk.
type ProviderProtocolEndpointCreateBulk struct {
	config
	err      error
	builders []*ProviderProtocolEndpointCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderProtocolEndpoint entities in the database.
func (_c *ProviderProtocolEndpointCreateBulk) Save(ctx context.Context) ([]*ProviderProtocolEndpoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderProtocolEndpoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderProtocolEndpointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderProtocolEndpointCreateBulk) SaveX(ctx context.Context) []*ProviderProtocolEndpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderProtocolEndpointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderProtocolEndpointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderProtocolEndpoint.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderProtocolEndpointUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderProtocolEndpointCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderProtocolEndpointUpsertBulk {
	_c.conflict = opts
	return &ProviderProtocolEndpointUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderProtocolEndpointCreateBulk) OnConflictColumns(columns ...string) *ProviderProtocolEndpointUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderProtocolEndpointUpsertBulk{
		create: _c,
	}
}

// ProviderProtocolEndpointUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderProtocolEndpoint nodes.
type ProviderProtocolEndpointUpsertBulk struct {
	create *ProviderProtocolEndpointCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderProtocolEndpointUpsertBulk) UpdateNewValues() *ProviderProtocolEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(providerprotocolendpoint.FieldCreatedAt)
			}
			if _, exists := b.mutation.ProviderID(); exists {
				s.SetIgnore(providerprotocolendpoint.FieldProviderID)
			}
			if _, exists := b.mutation.ProtocolFamily(); exists {
				s.SetIgnore(providerprotocolendpoint.FieldProtocolFamily)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderProtocolEndpoint.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderProtocolEndpointUpsertBulk) Ignore() *ProviderProtocolEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderProtocolEndpointUpsertBulk) DoNothing() *ProviderProtocolEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderProtocolEndpointCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderProtocolEndpointUpsertBulk) Update(set func(*ProviderProtocolEndpointUpsert)) *ProviderProtocolEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderProtocolEndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetUpdatedAt(v time.Time) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateUpdatedAt() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWireProfile sets the "wire_profile" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetWireProfile(v string) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetWireProfile(v)
	})
}

// UpdateWireProfile sets the "wire_profile" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateWireProfile() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateWireProfile()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetBaseURL(v string) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateBaseURL() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *ProviderProtocolEndpointUpsertBulk) ClearBaseURL() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.ClearBaseURL()
	})
}

// SetPath sets the "path" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetPath(v string) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdatePath() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdatePath()
	})
}

// SetAuthType sets the "auth_type" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetAuthType(v string) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetAuthType(v)
	})
}

// UpdateAuthType sets the "auth_type" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateAuthType() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateAuthType()
	})
}

// ClearAuthType clears the value of the "auth_type" field.
func (u *ProviderProtocolEndpointUpsertBulk) ClearAuthType() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.ClearAuthType()
	})
}

// SetHeaders sets the "headers" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetHeaders(v map[string]string) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateHeaders() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateHeaders()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetEnabled(v bool) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateEnabled() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateEnabled()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderProtocolEndpointUpsertBulk) SetVersion(v int64) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderProtocolEndpointUpsertBulk) AddVersion(v int64) *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderProtocolEndpointUpsertBulk) UpdateVersion() *ProviderProtocolEndpointUpsertBulk {
	return u.Update(func(s *ProviderProtocolEndpointUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *ProviderProtocolEndpointUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderProtocolEndpointCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderProtocolEndpointCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderProtocolEndpointUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
