// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referral"
)

// Referral is the model entity for the Referral schema.
type Referral struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ReferrerID holds the value of the "referrer_id" field.
	ReferrerID int64 `json:"referrer_id,omitempty"`
	// RefereeID holds the value of the "referee_id" field.
	RefereeID int64 `json:"referee_id,omitempty"`
	// ReferralCode holds the value of the "referral_code" field.
	ReferralCode string `json:"referral_code,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InviteeRewardAmount holds the value of the "invitee_reward_amount" field.
	InviteeRewardAmount float64 `json:"invitee_reward_amount,omitempty"`
	// InviterRewardAmount holds the value of the "inviter_reward_amount" field.
	InviterRewardAmount float64 `json:"inviter_reward_amount,omitempty"`
	// InviteeRewardedAt holds the value of the "invitee_rewarded_at" field.
	InviteeRewardedAt *time.Time `json:"invitee_rewarded_at,omitempty"`
	// InviterRewardedAt holds the value of the "inviter_rewarded_at" field.
	InviterRewardedAt *time.Time `json:"inviter_rewarded_at,omitempty"`
	// OngoingRewardCount holds the value of the "ongoing_reward_count" field.
	OngoingRewardCount int `json:"ongoing_reward_count,omitempty"`
	// OngoingRewardTotal holds the value of the "ongoing_reward_total" field.
	OngoingRewardTotal float64 `json:"ongoing_reward_total,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Referral) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referral.FieldInviteeRewardAmount, referral.FieldInviterRewardAmount, referral.FieldOngoingRewardTotal:
			values[i] = new(sql.NullFloat64)
		case referral.FieldID, referral.FieldReferrerID, referral.FieldRefereeID, referral.FieldOngoingRewardCount:
			values[i] = new(sql.NullInt64)
		case referral.FieldReferralCode, referral.FieldStatus:
			values[i] = new(sql.NullString)
		case referral.FieldInviteeRewardedAt, referral.FieldInviterRewardedAt, referral.FieldCreatedAt, referral.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Referral fields.
func (_m *Referral) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referral.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referral.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = value.Int64
			}
		case referral.FieldRefereeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referee_id", values[i])
			} else if value.Valid {
				_m.RefereeID = value.Int64
			}
		case referral.FieldReferralCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referral_code", values[i])
			} else if value.Valid {
				_m.ReferralCode = value.String
			}
		case referral.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referral.FieldInviteeRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_reward_amount", values[i])
			} else if value.Valid {
				_m.InviteeRewardAmount = value.Float64
			}
		case referral.FieldInviterRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_reward_amount", values[i])
			} else if value.Valid {
				_m.InviterRewardAmount = value.Float64
			}
		case referral.FieldInviteeRewardedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_rewarded_at", values[i])
			} else if value.Valid {
				_m.InviteeRewardedAt = new(time.Time)
				*_m.InviteeRewardedAt = value.Time
			}
		case referral.FieldInviterRewardedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_rewarded_at", values[i])
			} else if value.Valid {
				_m.InviterRewardedAt = new(time.Time)
				*_m.InviterRewardedAt = value.Time
			}
		case referral.FieldOngoingRewardCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ongoing_reward_count", values[i])
			} else if value.Valid {
				_m.OngoingRewardCount = int(value.Int64)
			}
		case referral.FieldOngoingRewardTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ongoing_reward_total", values[i])
			} else if value.Valid {
				_m.OngoingRewardTotal = value.Float64
			}
		case referral.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case referral.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Referral.
// This includes values selected through modifiers, order, etc.
func (_m *Referral) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Referral.
// Note that you need to call Referral.Unwrap() before calling this method if this Referral
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Referral) Update() *ReferralUpdateOne {
	return NewReferralClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Referral entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Referral) Unwrap() *Referral {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Referral is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Referral) String() string {
	var builder strings.Builder
	builder.WriteString("Referral(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("referee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefereeID))
	builder.WriteString(", ")
	builder.WriteString("referral_code=")
	builder.WriteString(_m.ReferralCode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("invitee_reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeRewardAmount))
	builder.WriteString(", ")
	builder.WriteString("inviter_reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterRewardAmount))
	builder.WriteString(", ")
	if v := _m.InviteeRewardedAt; v != nil {
		builder.WriteString("invitee_rewarded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.InviterRewardedAt; v != nil {
		builder.WriteString("inviter_rewarded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ongoing_reward_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.OngoingRewardCount))
	builder.WriteString(", ")
	builder.WriteString("ongoing_reward_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.OngoingRewardTotal))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Referrals is a parsable slice of Referral.
type Referrals []*Referral
