// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/salescommissionmonthlysnapshot"
)

// SalesCommissionMonthlySnapshotUpdate is the builder for updating SalesCommissionMonthlySnapshot entities.
type SalesCommissionMonthlySnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SalesCommissionMonthlySnapshotMutation
}

// Where appends a list predicates to the SalesCommissionMonthlySnapshotUpdate builder.
func (_u *SalesCommissionMonthlySnapshotUpdate) Where(ps ...predicate.SalesCommissionMonthlySnapshot) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetSalesUserID(v int64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableSalesUserID(v *int64) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) AddSalesUserID(v int64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetCommissionMonth sets the "commission_month" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetCommissionMonth(v time.Time) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.SetCommissionMonth(v)
	return _u
}

// SetNillableCommissionMonth sets the "commission_month" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableCommissionMonth(v *time.Time) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetCommissionMonth(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetTimezone(v string) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableTimezone(v *string) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCommissionMode sets the "commission_mode" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetCommissionMode(v string) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.SetCommissionMode(v)
	return _u
}

// SetNillableCommissionMode sets the "commission_mode" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableCommissionMode(v *string) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetCommissionMode(*v)
	}
	return _u
}

// SetFixedCommissionRate sets the "fixed_commission_rate" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetFixedCommissionRate(v float64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.ResetFixedCommissionRate()
	_u.mutation.SetFixedCommissionRate(v)
	return _u
}

// SetNillableFixedCommissionRate sets the "fixed_commission_rate" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableFixedCommissionRate(v *float64) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetFixedCommissionRate(*v)
	}
	return _u
}

// AddFixedCommissionRate adds value to the "fixed_commission_rate" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) AddFixedCommissionRate(v float64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.AddFixedCommissionRate(v)
	return _u
}

// SetMinMonthlySalesCny sets the "min_monthly_sales_cny" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetMinMonthlySalesCny(v float64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.ResetMinMonthlySalesCny()
	_u.mutation.SetMinMonthlySalesCny(v)
	return _u
}

// SetNillableMinMonthlySalesCny sets the "min_monthly_sales_cny" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetNillableMinMonthlySalesCny(v *float64) *SalesCommissionMonthlySnapshotUpdate {
	if v != nil {
		_u.SetMinMonthlySalesCny(*v)
	}
	return _u
}

// AddMinMonthlySalesCny adds value to the "min_monthly_sales_cny" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) AddMinMonthlySalesCny(v float64) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.AddMinMonthlySalesCny(v)
	return _u
}

// SetTiersJSON sets the "tiers_json" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetTiersJSON(v []map[string]interface{}) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.SetTiersJSON(v)
	return _u
}

// AppendTiersJSON appends value to the "tiers_json" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) AppendTiersJSON(v []map[string]interface{}) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.AppendTiersJSON(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionMonthlySnapshotUpdate) SetUpdatedAt(v time.Time) *SalesCommissionMonthlySnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionMonthlySnapshotMutation object of the builder.
func (_u *SalesCommissionMonthlySnapshotUpdate) Mutation() *SalesCommissionMonthlySnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SalesCommissionMonthlySnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionMonthlySnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SalesCommissionMonthlySnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionMonthlySnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionMonthlySnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissionmonthlysnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionMonthlySnapshotUpdate) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := salescommissionmonthlysnapshot.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionMonthlySnapshot.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommissionMode(); ok {
		if err := salescommissionmonthlysnapshot.CommissionModeValidator(v); err != nil {
			return &ValidationError{Name: "commission_mode", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionMonthlySnapshot.commission_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionMonthlySnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissionmonthlysnapshot.Table, salescommissionmonthlysnapshot.Columns, sqlgraph.NewFieldSpec(salescommissionmonthlysnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommissionMonth(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldCommissionMonth, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommissionMode(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldCommissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FixedCommissionRate(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldFixedCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFixedCommissionRate(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldFixedCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinMonthlySalesCny(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldMinMonthlySalesCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinMonthlySalesCny(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldMinMonthlySalesCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TiersJSON(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldTiersJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTiersJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, salescommissionmonthlysnapshot.FieldTiersJSON, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissionmonthlysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SalesCommissionMonthlySnapshotUpdateOne is the builder for updating a single SalesCommissionMonthlySnapshot entity.
type SalesCommissionMonthlySnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SalesCommissionMonthlySnapshotMutation
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetSalesUserID(v int64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableSalesUserID(v *int64) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) AddSalesUserID(v int64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetCommissionMonth sets the "commission_month" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetCommissionMonth(v time.Time) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.SetCommissionMonth(v)
	return _u
}

// SetNillableCommissionMonth sets the "commission_month" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableCommissionMonth(v *time.Time) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetCommissionMonth(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetTimezone(v string) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableTimezone(v *string) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCommissionMode sets the "commission_mode" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetCommissionMode(v string) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.SetCommissionMode(v)
	return _u
}

// SetNillableCommissionMode sets the "commission_mode" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableCommissionMode(v *string) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetCommissionMode(*v)
	}
	return _u
}

// SetFixedCommissionRate sets the "fixed_commission_rate" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetFixedCommissionRate(v float64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.ResetFixedCommissionRate()
	_u.mutation.SetFixedCommissionRate(v)
	return _u
}

// SetNillableFixedCommissionRate sets the "fixed_commission_rate" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableFixedCommissionRate(v *float64) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetFixedCommissionRate(*v)
	}
	return _u
}

// AddFixedCommissionRate adds value to the "fixed_commission_rate" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) AddFixedCommissionRate(v float64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.AddFixedCommissionRate(v)
	return _u
}

// SetMinMonthlySalesCny sets the "min_monthly_sales_cny" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetMinMonthlySalesCny(v float64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.ResetMinMonthlySalesCny()
	_u.mutation.SetMinMonthlySalesCny(v)
	return _u
}

// SetNillableMinMonthlySalesCny sets the "min_monthly_sales_cny" field if the given value is not nil.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetNillableMinMonthlySalesCny(v *float64) *SalesCommissionMonthlySnapshotUpdateOne {
	if v != nil {
		_u.SetMinMonthlySalesCny(*v)
	}
	return _u
}

// AddMinMonthlySalesCny adds value to the "min_monthly_sales_cny" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) AddMinMonthlySalesCny(v float64) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.AddMinMonthlySalesCny(v)
	return _u
}

// SetTiersJSON sets the "tiers_json" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetTiersJSON(v []map[string]interface{}) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.SetTiersJSON(v)
	return _u
}

// AppendTiersJSON appends value to the "tiers_json" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) AppendTiersJSON(v []map[string]interface{}) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.AppendTiersJSON(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SetUpdatedAt(v time.Time) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionMonthlySnapshotMutation object of the builder.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) Mutation() *SalesCommissionMonthlySnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the SalesCommissionMonthlySnapshotUpdate builder.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) Where(ps ...predicate.SalesCommissionMonthlySnapshot) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) Select(field string, fields ...string) *SalesCommissionMonthlySnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SalesCommissionMonthlySnapshot entity.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) Save(ctx context.Context) (*SalesCommissionMonthlySnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) SaveX(ctx context.Context) *SalesCommissionMonthlySnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissionmonthlysnapshot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionMonthlySnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := salescommissionmonthlysnapshot.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionMonthlySnapshot.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommissionMode(); ok {
		if err := salescommissionmonthlysnapshot.CommissionModeValidator(v); err != nil {
			return &ValidationError{Name: "commission_mode", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionMonthlySnapshot.commission_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionMonthlySnapshotUpdateOne) sqlSave(ctx context.Context) (_node *SalesCommissionMonthlySnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissionmonthlysnapshot.Table, salescommissionmonthlysnapshot.Columns, sqlgraph.NewFieldSpec(salescommissionmonthlysnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SalesCommissionMonthlySnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salescommissionmonthlysnapshot.FieldID)
		for _, f := range fields {
			if !salescommissionmonthlysnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salescommissionmonthlysnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CommissionMonth(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldCommissionMonth, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommissionMode(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldCommissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FixedCommissionRate(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldFixedCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFixedCommissionRate(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldFixedCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinMonthlySalesCny(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldMinMonthlySalesCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinMonthlySalesCny(); ok {
		_spec.AddField(salescommissionmonthlysnapshot.FieldMinMonthlySalesCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TiersJSON(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldTiersJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTiersJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, salescommissionmonthlysnapshot.FieldTiersJSON, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissionmonthlysnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SalesCommissionMonthlySnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissionmonthlysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
