// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/salescommissiontier"
)

// SalesCommissionTierUpdate is the builder for updating SalesCommissionTier entities.
type SalesCommissionTierUpdate struct {
	config
	hooks    []Hook
	mutation *SalesCommissionTierMutation
}

// Where appends a list predicates to the SalesCommissionTierUpdate builder.
func (_u *SalesCommissionTierUpdate) Where(ps ...predicate.SalesCommissionTier) *SalesCommissionTierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionTierUpdate) SetSalesUserID(v int64) *SalesCommissionTierUpdate {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionTierUpdate) SetNillableSalesUserID(v *int64) *SalesCommissionTierUpdate {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionTierUpdate) AddSalesUserID(v int64) *SalesCommissionTierUpdate {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetMonthSalesFromCny sets the "month_sales_from_cny" field.
func (_u *SalesCommissionTierUpdate) SetMonthSalesFromCny(v float64) *SalesCommissionTierUpdate {
	_u.mutation.ResetMonthSalesFromCny()
	_u.mutation.SetMonthSalesFromCny(v)
	return _u
}

// SetNillableMonthSalesFromCny sets the "month_sales_from_cny" field if the given value is not nil.
func (_u *SalesCommissionTierUpdate) SetNillableMonthSalesFromCny(v *float64) *SalesCommissionTierUpdate {
	if v != nil {
		_u.SetMonthSalesFromCny(*v)
	}
	return _u
}

// AddMonthSalesFromCny adds value to the "month_sales_from_cny" field.
func (_u *SalesCommissionTierUpdate) AddMonthSalesFromCny(v float64) *SalesCommissionTierUpdate {
	_u.mutation.AddMonthSalesFromCny(v)
	return _u
}

// SetMonthSalesToCny sets the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdate) SetMonthSalesToCny(v float64) *SalesCommissionTierUpdate {
	_u.mutation.ResetMonthSalesToCny()
	_u.mutation.SetMonthSalesToCny(v)
	return _u
}

// SetNillableMonthSalesToCny sets the "month_sales_to_cny" field if the given value is not nil.
func (_u *SalesCommissionTierUpdate) SetNillableMonthSalesToCny(v *float64) *SalesCommissionTierUpdate {
	if v != nil {
		_u.SetMonthSalesToCny(*v)
	}
	return _u
}

// AddMonthSalesToCny adds value to the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdate) AddMonthSalesToCny(v float64) *SalesCommissionTierUpdate {
	_u.mutation.AddMonthSalesToCny(v)
	return _u
}

// ClearMonthSalesToCny clears the value of the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdate) ClearMonthSalesToCny() *SalesCommissionTierUpdate {
	_u.mutation.ClearMonthSalesToCny()
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *SalesCommissionTierUpdate) SetCommissionRate(v float64) *SalesCommissionTierUpdate {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *SalesCommissionTierUpdate) SetNillableCommissionRate(v *float64) *SalesCommissionTierUpdate {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *SalesCommissionTierUpdate) AddCommissionRate(v float64) *SalesCommissionTierUpdate {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SalesCommissionTierUpdate) SetSortOrder(v int) *SalesCommissionTierUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SalesCommissionTierUpdate) SetNillableSortOrder(v *int) *SalesCommissionTierUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SalesCommissionTierUpdate) AddSortOrder(v int) *SalesCommissionTierUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionTierUpdate) SetUpdatedAt(v time.Time) *SalesCommissionTierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionTierMutation object of the builder.
func (_u *SalesCommissionTierUpdate) Mutation() *SalesCommissionTierMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SalesCommissionTierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionTierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SalesCommissionTierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionTierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionTierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissiontier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionTierUpdate) check() error {
	if v, ok := _u.mutation.CommissionRate(); ok {
		if err := salescommissiontier.CommissionRateValidator(v); err != nil {
			return &ValidationError{Name: "commission_rate", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionTier.commission_rate": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionTierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissiontier.Table, salescommissiontier.Columns, sqlgraph.NewFieldSpec(salescommissiontier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissiontier.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissiontier.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MonthSalesFromCny(); ok {
		_spec.SetField(salescommissiontier.FieldMonthSalesFromCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthSalesFromCny(); ok {
		_spec.AddField(salescommissiontier.FieldMonthSalesFromCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthSalesToCny(); ok {
		_spec.SetField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthSalesToCny(); ok {
		_spec.AddField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64, value)
	}
	if _u.mutation.MonthSalesToCnyCleared() {
		_spec.ClearField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(salescommissiontier.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(salescommissiontier.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(salescommissiontier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(salescommissiontier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissiontier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissiontier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SalesCommissionTierUpdateOne is the builder for updating a single SalesCommissionTier entity.
type SalesCommissionTierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SalesCommissionTierMutation
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionTierUpdateOne) SetSalesUserID(v int64) *SalesCommissionTierUpdateOne {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionTierUpdateOne) SetNillableSalesUserID(v *int64) *SalesCommissionTierUpdateOne {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionTierUpdateOne) AddSalesUserID(v int64) *SalesCommissionTierUpdateOne {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetMonthSalesFromCny sets the "month_sales_from_cny" field.
func (_u *SalesCommissionTierUpdateOne) SetMonthSalesFromCny(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.ResetMonthSalesFromCny()
	_u.mutation.SetMonthSalesFromCny(v)
	return _u
}

// SetNillableMonthSalesFromCny sets the "month_sales_from_cny" field if the given value is not nil.
func (_u *SalesCommissionTierUpdateOne) SetNillableMonthSalesFromCny(v *float64) *SalesCommissionTierUpdateOne {
	if v != nil {
		_u.SetMonthSalesFromCny(*v)
	}
	return _u
}

// AddMonthSalesFromCny adds value to the "month_sales_from_cny" field.
func (_u *SalesCommissionTierUpdateOne) AddMonthSalesFromCny(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.AddMonthSalesFromCny(v)
	return _u
}

// SetMonthSalesToCny sets the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdateOne) SetMonthSalesToCny(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.ResetMonthSalesToCny()
	_u.mutation.SetMonthSalesToCny(v)
	return _u
}

// SetNillableMonthSalesToCny sets the "month_sales_to_cny" field if the given value is not nil.
func (_u *SalesCommissionTierUpdateOne) SetNillableMonthSalesToCny(v *float64) *SalesCommissionTierUpdateOne {
	if v != nil {
		_u.SetMonthSalesToCny(*v)
	}
	return _u
}

// AddMonthSalesToCny adds value to the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdateOne) AddMonthSalesToCny(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.AddMonthSalesToCny(v)
	return _u
}

// ClearMonthSalesToCny clears the value of the "month_sales_to_cny" field.
func (_u *SalesCommissionTierUpdateOne) ClearMonthSalesToCny() *SalesCommissionTierUpdateOne {
	_u.mutation.ClearMonthSalesToCny()
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *SalesCommissionTierUpdateOne) SetCommissionRate(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *SalesCommissionTierUpdateOne) SetNillableCommissionRate(v *float64) *SalesCommissionTierUpdateOne {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *SalesCommissionTierUpdateOne) AddCommissionRate(v float64) *SalesCommissionTierUpdateOne {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SalesCommissionTierUpdateOne) SetSortOrder(v int) *SalesCommissionTierUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SalesCommissionTierUpdateOne) SetNillableSortOrder(v *int) *SalesCommissionTierUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SalesCommissionTierUpdateOne) AddSortOrder(v int) *SalesCommissionTierUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionTierUpdateOne) SetUpdatedAt(v time.Time) *SalesCommissionTierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionTierMutation object of the builder.
func (_u *SalesCommissionTierUpdateOne) Mutation() *SalesCommissionTierMutation {
	return _u.mutation
}

// Where appends a list predicates to the SalesCommissionTierUpdate builder.
func (_u *SalesCommissionTierUpdateOne) Where(ps ...predicate.SalesCommissionTier) *SalesCommissionTierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SalesCommissionTierUpdateOne) Select(field string, fields ...string) *SalesCommissionTierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SalesCommissionTier entity.
func (_u *SalesCommissionTierUpdateOne) Save(ctx context.Context) (*SalesCommissionTier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionTierUpdateOne) SaveX(ctx context.Context) *SalesCommissionTier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SalesCommissionTierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionTierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionTierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissiontier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionTierUpdateOne) check() error {
	if v, ok := _u.mutation.CommissionRate(); ok {
		if err := salescommissiontier.CommissionRateValidator(v); err != nil {
			return &ValidationError{Name: "commission_rate", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionTier.commission_rate": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionTierUpdateOne) sqlSave(ctx context.Context) (_node *SalesCommissionTier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissiontier.Table, salescommissiontier.Columns, sqlgraph.NewFieldSpec(salescommissiontier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SalesCommissionTier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salescommissiontier.FieldID)
		for _, f := range fields {
			if !salescommissiontier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salescommissiontier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissiontier.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissiontier.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MonthSalesFromCny(); ok {
		_spec.SetField(salescommissiontier.FieldMonthSalesFromCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthSalesFromCny(); ok {
		_spec.AddField(salescommissiontier.FieldMonthSalesFromCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthSalesToCny(); ok {
		_spec.SetField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthSalesToCny(); ok {
		_spec.AddField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64, value)
	}
	if _u.mutation.MonthSalesToCnyCleared() {
		_spec.ClearField(salescommissiontier.FieldMonthSalesToCny, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(salescommissiontier.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(salescommissiontier.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(salescommissiontier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(salescommissiontier.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissiontier.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SalesCommissionTier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissiontier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
