// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/salescommissionsettlement"
)

// SalesCommissionSettlement is the model entity for the SalesCommissionSettlement schema.
type SalesCommissionSettlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SalesUserID holds the value of the "sales_user_id" field.
	SalesUserID int64 `json:"sales_user_id,omitempty"`
	// AmountCny holds the value of the "amount_cny" field.
	AmountCny float64 `json:"amount_cny,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SalesCommissionSettlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case salescommissionsettlement.FieldAmountCny:
			values[i] = new(sql.NullFloat64)
		case salescommissionsettlement.FieldID, salescommissionsettlement.FieldSalesUserID, salescommissionsettlement.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case salescommissionsettlement.FieldNote:
			values[i] = new(sql.NullString)
		case salescommissionsettlement.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SalesCommissionSettlement fields.
func (_m *SalesCommissionSettlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case salescommissionsettlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case salescommissionsettlement.FieldSalesUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sales_user_id", values[i])
			} else if value.Valid {
				_m.SalesUserID = value.Int64
			}
		case salescommissionsettlement.FieldAmountCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cny", values[i])
			} else if value.Valid {
				_m.AmountCny = value.Float64
			}
		case salescommissionsettlement.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case salescommissionsettlement.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case salescommissionsettlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SalesCommissionSettlement.
// This includes values selected through modifiers, order, etc.
func (_m *SalesCommissionSettlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SalesCommissionSettlement.
// Note that you need to call SalesCommissionSettlement.Unwrap() before calling this method if this SalesCommissionSettlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SalesCommissionSettlement) Update() *SalesCommissionSettlementUpdateOne {
	return NewSalesCommissionSettlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SalesCommissionSettlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SalesCommissionSettlement) Unwrap() *SalesCommissionSettlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SalesCommissionSettlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SalesCommissionSettlement) String() string {
	var builder strings.Builder
	builder.WriteString("SalesCommissionSettlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sales_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SalesUserID))
	builder.WriteString(", ")
	builder.WriteString("amount_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCny))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SalesCommissionSettlements is a parsable slice of SalesCommissionSettlement.
type SalesCommissionSettlements []*SalesCommissionSettlement
