// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/salescommissionrecord"
)

// SalesCommissionRecordUpdate is the builder for updating SalesCommissionRecord entities.
type SalesCommissionRecordUpdate struct {
	config
	hooks    []Hook
	mutation *SalesCommissionRecordMutation
}

// Where appends a list predicates to the SalesCommissionRecordUpdate builder.
func (_u *SalesCommissionRecordUpdate) Where(ps ...predicate.SalesCommissionRecord) *SalesCommissionRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionRecordUpdate) SetSalesUserID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableSalesUserID(v *int64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionRecordUpdate) AddSalesUserID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetRefereeUserID sets the "referee_user_id" field.
func (_u *SalesCommissionRecordUpdate) SetRefereeUserID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetRefereeUserID()
	_u.mutation.SetRefereeUserID(v)
	return _u
}

// SetNillableRefereeUserID sets the "referee_user_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableRefereeUserID(v *int64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetRefereeUserID(*v)
	}
	return _u
}

// AddRefereeUserID adds value to the "referee_user_id" field.
func (_u *SalesCommissionRecordUpdate) AddRefereeUserID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.AddRefereeUserID(v)
	return _u
}

// SetReferralID sets the "referral_id" field.
func (_u *SalesCommissionRecordUpdate) SetReferralID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetReferralID()
	_u.mutation.SetReferralID(v)
	return _u
}

// SetNillableReferralID sets the "referral_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableReferralID(v *int64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetReferralID(*v)
	}
	return _u
}

// AddReferralID adds value to the "referral_id" field.
func (_u *SalesCommissionRecordUpdate) AddReferralID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.AddReferralID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SalesCommissionRecordUpdate) SetPaymentOrderID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillablePaymentOrderID(v *int64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SalesCommissionRecordUpdate) AddPaymentOrderID(v int64) *SalesCommissionRecordUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetOrderPayAmountCny sets the "order_pay_amount_cny" field.
func (_u *SalesCommissionRecordUpdate) SetOrderPayAmountCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetOrderPayAmountCny()
	_u.mutation.SetOrderPayAmountCny(v)
	return _u
}

// SetNillableOrderPayAmountCny sets the "order_pay_amount_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableOrderPayAmountCny(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetOrderPayAmountCny(*v)
	}
	return _u
}

// AddOrderPayAmountCny adds value to the "order_pay_amount_cny" field.
func (_u *SalesCommissionRecordUpdate) AddOrderPayAmountCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddOrderPayAmountCny(v)
	return _u
}

// SetOrderCreditedAmount sets the "order_credited_amount" field.
func (_u *SalesCommissionRecordUpdate) SetOrderCreditedAmount(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetOrderCreditedAmount()
	_u.mutation.SetOrderCreditedAmount(v)
	return _u
}

// SetNillableOrderCreditedAmount sets the "order_credited_amount" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableOrderCreditedAmount(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetOrderCreditedAmount(*v)
	}
	return _u
}

// AddOrderCreditedAmount adds value to the "order_credited_amount" field.
func (_u *SalesCommissionRecordUpdate) AddOrderCreditedAmount(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddOrderCreditedAmount(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *SalesCommissionRecordUpdate) SetCommissionRate(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableCommissionRate(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *SalesCommissionRecordUpdate) AddCommissionRate(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetCommissionTotalCny sets the "commission_total_cny" field.
func (_u *SalesCommissionRecordUpdate) SetCommissionTotalCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetCommissionTotalCny()
	_u.mutation.SetCommissionTotalCny(v)
	return _u
}

// SetNillableCommissionTotalCny sets the "commission_total_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableCommissionTotalCny(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetCommissionTotalCny(*v)
	}
	return _u
}

// AddCommissionTotalCny adds value to the "commission_total_cny" field.
func (_u *SalesCommissionRecordUpdate) AddCommissionTotalCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddCommissionTotalCny(v)
	return _u
}

// SetCreditedUsedAmount sets the "credited_used_amount" field.
func (_u *SalesCommissionRecordUpdate) SetCreditedUsedAmount(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetCreditedUsedAmount()
	_u.mutation.SetCreditedUsedAmount(v)
	return _u
}

// SetNillableCreditedUsedAmount sets the "credited_used_amount" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableCreditedUsedAmount(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetCreditedUsedAmount(*v)
	}
	return _u
}

// AddCreditedUsedAmount adds value to the "credited_used_amount" field.
func (_u *SalesCommissionRecordUpdate) AddCreditedUsedAmount(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddCreditedUsedAmount(v)
	return _u
}

// SetUnlockedCny sets the "unlocked_cny" field.
func (_u *SalesCommissionRecordUpdate) SetUnlockedCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetUnlockedCny()
	_u.mutation.SetUnlockedCny(v)
	return _u
}

// SetNillableUnlockedCny sets the "unlocked_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableUnlockedCny(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetUnlockedCny(*v)
	}
	return _u
}

// AddUnlockedCny adds value to the "unlocked_cny" field.
func (_u *SalesCommissionRecordUpdate) AddUnlockedCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddUnlockedCny(v)
	return _u
}

// SetSettledCny sets the "settled_cny" field.
func (_u *SalesCommissionRecordUpdate) SetSettledCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.ResetSettledCny()
	_u.mutation.SetSettledCny(v)
	return _u
}

// SetNillableSettledCny sets the "settled_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableSettledCny(v *float64) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetSettledCny(*v)
	}
	return _u
}

// AddSettledCny adds value to the "settled_cny" field.
func (_u *SalesCommissionRecordUpdate) AddSettledCny(v float64) *SalesCommissionRecordUpdate {
	_u.mutation.AddSettledCny(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SalesCommissionRecordUpdate) SetStatus(v string) *SalesCommissionRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableStatus(v *string) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *SalesCommissionRecordUpdate) SetNote(v string) *SalesCommissionRecordUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdate) SetNillableNote(v *string) *SalesCommissionRecordUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionRecordUpdate) SetUpdatedAt(v time.Time) *SalesCommissionRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionRecordMutation object of the builder.
func (_u *SalesCommissionRecordUpdate) Mutation() *SalesCommissionRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SalesCommissionRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SalesCommissionRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionRecordUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := salescommissionrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissionrecord.Table, salescommissionrecord.Columns, sqlgraph.NewFieldSpec(salescommissionrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissionrecord.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissionrecord.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefereeUserID(); ok {
		_spec.SetField(salescommissionrecord.FieldRefereeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefereeUserID(); ok {
		_spec.AddField(salescommissionrecord.FieldRefereeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReferralID(); ok {
		_spec.SetField(salescommissionrecord.FieldReferralID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferralID(); ok {
		_spec.AddField(salescommissionrecord.FieldReferralID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(salescommissionrecord.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(salescommissionrecord.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderPayAmountCny(); ok {
		_spec.SetField(salescommissionrecord.FieldOrderPayAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderPayAmountCny(); ok {
		_spec.AddField(salescommissionrecord.FieldOrderPayAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderCreditedAmount(); ok {
		_spec.SetField(salescommissionrecord.FieldOrderCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderCreditedAmount(); ok {
		_spec.AddField(salescommissionrecord.FieldOrderCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(salescommissionrecord.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(salescommissionrecord.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionTotalCny(); ok {
		_spec.SetField(salescommissionrecord.FieldCommissionTotalCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionTotalCny(); ok {
		_spec.AddField(salescommissionrecord.FieldCommissionTotalCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedUsedAmount(); ok {
		_spec.SetField(salescommissionrecord.FieldCreditedUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedUsedAmount(); ok {
		_spec.AddField(salescommissionrecord.FieldCreditedUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnlockedCny(); ok {
		_spec.SetField(salescommissionrecord.FieldUnlockedCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnlockedCny(); ok {
		_spec.AddField(salescommissionrecord.FieldUnlockedCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledCny(); ok {
		_spec.SetField(salescommissionrecord.FieldSettledCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledCny(); ok {
		_spec.AddField(salescommissionrecord.FieldSettledCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(salescommissionrecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(salescommissionrecord.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SalesCommissionRecordUpdateOne is the builder for updating a single SalesCommissionRecord entity.
type SalesCommissionRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SalesCommissionRecordMutation
}

// SetSalesUserID sets the "sales_user_id" field.
func (_u *SalesCommissionRecordUpdateOne) SetSalesUserID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetSalesUserID()
	_u.mutation.SetSalesUserID(v)
	return _u
}

// SetNillableSalesUserID sets the "sales_user_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableSalesUserID(v *int64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetSalesUserID(*v)
	}
	return _u
}

// AddSalesUserID adds value to the "sales_user_id" field.
func (_u *SalesCommissionRecordUpdateOne) AddSalesUserID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddSalesUserID(v)
	return _u
}

// SetRefereeUserID sets the "referee_user_id" field.
func (_u *SalesCommissionRecordUpdateOne) SetRefereeUserID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetRefereeUserID()
	_u.mutation.SetRefereeUserID(v)
	return _u
}

// SetNillableRefereeUserID sets the "referee_user_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableRefereeUserID(v *int64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetRefereeUserID(*v)
	}
	return _u
}

// AddRefereeUserID adds value to the "referee_user_id" field.
func (_u *SalesCommissionRecordUpdateOne) AddRefereeUserID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddRefereeUserID(v)
	return _u
}

// SetReferralID sets the "referral_id" field.
func (_u *SalesCommissionRecordUpdateOne) SetReferralID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetReferralID()
	_u.mutation.SetReferralID(v)
	return _u
}

// SetNillableReferralID sets the "referral_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableReferralID(v *int64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetReferralID(*v)
	}
	return _u
}

// AddReferralID adds value to the "referral_id" field.
func (_u *SalesCommissionRecordUpdateOne) AddReferralID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddReferralID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SalesCommissionRecordUpdateOne) SetPaymentOrderID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillablePaymentOrderID(v *int64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SalesCommissionRecordUpdateOne) AddPaymentOrderID(v int64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetOrderPayAmountCny sets the "order_pay_amount_cny" field.
func (_u *SalesCommissionRecordUpdateOne) SetOrderPayAmountCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetOrderPayAmountCny()
	_u.mutation.SetOrderPayAmountCny(v)
	return _u
}

// SetNillableOrderPayAmountCny sets the "order_pay_amount_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableOrderPayAmountCny(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetOrderPayAmountCny(*v)
	}
	return _u
}

// AddOrderPayAmountCny adds value to the "order_pay_amount_cny" field.
func (_u *SalesCommissionRecordUpdateOne) AddOrderPayAmountCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddOrderPayAmountCny(v)
	return _u
}

// SetOrderCreditedAmount sets the "order_credited_amount" field.
func (_u *SalesCommissionRecordUpdateOne) SetOrderCreditedAmount(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetOrderCreditedAmount()
	_u.mutation.SetOrderCreditedAmount(v)
	return _u
}

// SetNillableOrderCreditedAmount sets the "order_credited_amount" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableOrderCreditedAmount(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetOrderCreditedAmount(*v)
	}
	return _u
}

// AddOrderCreditedAmount adds value to the "order_credited_amount" field.
func (_u *SalesCommissionRecordUpdateOne) AddOrderCreditedAmount(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddOrderCreditedAmount(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *SalesCommissionRecordUpdateOne) SetCommissionRate(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableCommissionRate(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *SalesCommissionRecordUpdateOne) AddCommissionRate(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetCommissionTotalCny sets the "commission_total_cny" field.
func (_u *SalesCommissionRecordUpdateOne) SetCommissionTotalCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetCommissionTotalCny()
	_u.mutation.SetCommissionTotalCny(v)
	return _u
}

// SetNillableCommissionTotalCny sets the "commission_total_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableCommissionTotalCny(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetCommissionTotalCny(*v)
	}
	return _u
}

// AddCommissionTotalCny adds value to the "commission_total_cny" field.
func (_u *SalesCommissionRecordUpdateOne) AddCommissionTotalCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddCommissionTotalCny(v)
	return _u
}

// SetCreditedUsedAmount sets the "credited_used_amount" field.
func (_u *SalesCommissionRecordUpdateOne) SetCreditedUsedAmount(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetCreditedUsedAmount()
	_u.mutation.SetCreditedUsedAmount(v)
	return _u
}

// SetNillableCreditedUsedAmount sets the "credited_used_amount" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableCreditedUsedAmount(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetCreditedUsedAmount(*v)
	}
	return _u
}

// AddCreditedUsedAmount adds value to the "credited_used_amount" field.
func (_u *SalesCommissionRecordUpdateOne) AddCreditedUsedAmount(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddCreditedUsedAmount(v)
	return _u
}

// SetUnlockedCny sets the "unlocked_cny" field.
func (_u *SalesCommissionRecordUpdateOne) SetUnlockedCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetUnlockedCny()
	_u.mutation.SetUnlockedCny(v)
	return _u
}

// SetNillableUnlockedCny sets the "unlocked_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableUnlockedCny(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetUnlockedCny(*v)
	}
	return _u
}

// AddUnlockedCny adds value to the "unlocked_cny" field.
func (_u *SalesCommissionRecordUpdateOne) AddUnlockedCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddUnlockedCny(v)
	return _u
}

// SetSettledCny sets the "settled_cny" field.
func (_u *SalesCommissionRecordUpdateOne) SetSettledCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.ResetSettledCny()
	_u.mutation.SetSettledCny(v)
	return _u
}

// SetNillableSettledCny sets the "settled_cny" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableSettledCny(v *float64) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetSettledCny(*v)
	}
	return _u
}

// AddSettledCny adds value to the "settled_cny" field.
func (_u *SalesCommissionRecordUpdateOne) AddSettledCny(v float64) *SalesCommissionRecordUpdateOne {
	_u.mutation.AddSettledCny(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SalesCommissionRecordUpdateOne) SetStatus(v string) *SalesCommissionRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableStatus(v *string) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *SalesCommissionRecordUpdateOne) SetNote(v string) *SalesCommissionRecordUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SalesCommissionRecordUpdateOne) SetNillableNote(v *string) *SalesCommissionRecordUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SalesCommissionRecordUpdateOne) SetUpdatedAt(v time.Time) *SalesCommissionRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SalesCommissionRecordMutation object of the builder.
func (_u *SalesCommissionRecordUpdateOne) Mutation() *SalesCommissionRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the SalesCommissionRecordUpdate builder.
func (_u *SalesCommissionRecordUpdateOne) Where(ps ...predicate.SalesCommissionRecord) *SalesCommissionRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SalesCommissionRecordUpdateOne) Select(field string, fields ...string) *SalesCommissionRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SalesCommissionRecord entity.
func (_u *SalesCommissionRecordUpdateOne) Save(ctx context.Context) (*SalesCommissionRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesCommissionRecordUpdateOne) SaveX(ctx context.Context) *SalesCommissionRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SalesCommissionRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesCommissionRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SalesCommissionRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salescommissionrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesCommissionRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := salescommissionrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SalesCommissionRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SalesCommissionRecordUpdateOne) sqlSave(ctx context.Context) (_node *SalesCommissionRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salescommissionrecord.Table, salescommissionrecord.Columns, sqlgraph.NewFieldSpec(salescommissionrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SalesCommissionRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salescommissionrecord.FieldID)
		for _, f := range fields {
			if !salescommissionrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salescommissionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SalesUserID(); ok {
		_spec.SetField(salescommissionrecord.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSalesUserID(); ok {
		_spec.AddField(salescommissionrecord.FieldSalesUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefereeUserID(); ok {
		_spec.SetField(salescommissionrecord.FieldRefereeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefereeUserID(); ok {
		_spec.AddField(salescommissionrecord.FieldRefereeUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReferralID(); ok {
		_spec.SetField(salescommissionrecord.FieldReferralID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferralID(); ok {
		_spec.AddField(salescommissionrecord.FieldReferralID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(salescommissionrecord.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(salescommissionrecord.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderPayAmountCny(); ok {
		_spec.SetField(salescommissionrecord.FieldOrderPayAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderPayAmountCny(); ok {
		_spec.AddField(salescommissionrecord.FieldOrderPayAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderCreditedAmount(); ok {
		_spec.SetField(salescommissionrecord.FieldOrderCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderCreditedAmount(); ok {
		_spec.AddField(salescommissionrecord.FieldOrderCreditedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(salescommissionrecord.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(salescommissionrecord.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionTotalCny(); ok {
		_spec.SetField(salescommissionrecord.FieldCommissionTotalCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionTotalCny(); ok {
		_spec.AddField(salescommissionrecord.FieldCommissionTotalCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditedUsedAmount(); ok {
		_spec.SetField(salescommissionrecord.FieldCreditedUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditedUsedAmount(); ok {
		_spec.AddField(salescommissionrecord.FieldCreditedUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnlockedCny(); ok {
		_spec.SetField(salescommissionrecord.FieldUnlockedCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnlockedCny(); ok {
		_spec.AddField(salescommissionrecord.FieldUnlockedCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledCny(); ok {
		_spec.SetField(salescommissionrecord.FieldSettledCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledCny(); ok {
		_spec.AddField(salescommissionrecord.FieldSettledCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(salescommissionrecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(salescommissionrecord.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salescommissionrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SalesCommissionRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salescommissionrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
