// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/userreferralconfig"
)

// UserReferralConfigCreate is the builder for creating a UserReferralConfig entity.
type UserReferralConfigCreate struct {
	config
	mutation *UserReferralConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserReferralConfigCreate) SetUserID(v int64) *UserReferralConfigCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInviteeRewardAmount sets the "invitee_reward_amount" field.
func (_c *UserReferralConfigCreate) SetInviteeRewardAmount(v float64) *UserReferralConfigCreate {
	_c.mutation.SetInviteeRewardAmount(v)
	return _c
}

// SetNillableInviteeRewardAmount sets the "invitee_reward_amount" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableInviteeRewardAmount(v *float64) *UserReferralConfigCreate {
	if v != nil {
		_c.SetInviteeRewardAmount(*v)
	}
	return _c
}

// SetInviterRewardAmount sets the "inviter_reward_amount" field.
func (_c *UserReferralConfigCreate) SetInviterRewardAmount(v float64) *UserReferralConfigCreate {
	_c.mutation.SetInviterRewardAmount(v)
	return _c
}

// SetNillableInviterRewardAmount sets the "inviter_reward_amount" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableInviterRewardAmount(v *float64) *UserReferralConfigCreate {
	if v != nil {
		_c.SetInviterRewardAmount(*v)
	}
	return _c
}

// SetMaxInvites sets the "max_invites" field.
func (_c *UserReferralConfigCreate) SetMaxInvites(v int) *UserReferralConfigCreate {
	_c.mutation.SetMaxInvites(v)
	return _c
}

// SetNillableMaxInvites sets the "max_invites" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableMaxInvites(v *int) *UserReferralConfigCreate {
	if v != nil {
		_c.SetMaxInvites(*v)
	}
	return _c
}

// SetRewardExpiryDays sets the "reward_expiry_days" field.
func (_c *UserReferralConfigCreate) SetRewardExpiryDays(v int) *UserReferralConfigCreate {
	_c.mutation.SetRewardExpiryDays(v)
	return _c
}

// SetNillableRewardExpiryDays sets the "reward_expiry_days" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableRewardExpiryDays(v *int) *UserReferralConfigCreate {
	if v != nil {
		_c.SetRewardExpiryDays(*v)
	}
	return _c
}

// SetOngoingRewardEnabled sets the "ongoing_reward_enabled" field.
func (_c *UserReferralConfigCreate) SetOngoingRewardEnabled(v bool) *UserReferralConfigCreate {
	_c.mutation.SetOngoingRewardEnabled(v)
	return _c
}

// SetNillableOngoingRewardEnabled sets the "ongoing_reward_enabled" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableOngoingRewardEnabled(v *bool) *UserReferralConfigCreate {
	if v != nil {
		_c.SetOngoingRewardEnabled(*v)
	}
	return _c
}

// SetOngoingRewardAmount sets the "ongoing_reward_amount" field.
func (_c *UserReferralConfigCreate) SetOngoingRewardAmount(v float64) *UserReferralConfigCreate {
	_c.mutation.SetOngoingRewardAmount(v)
	return _c
}

// SetNillableOngoingRewardAmount sets the "ongoing_reward_amount" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableOngoingRewardAmount(v *float64) *UserReferralConfigCreate {
	if v != nil {
		_c.SetOngoingRewardAmount(*v)
	}
	return _c
}

// SetOngoingRewardPercent sets the "ongoing_reward_percent" field.
func (_c *UserReferralConfigCreate) SetOngoingRewardPercent(v float64) *UserReferralConfigCreate {
	_c.mutation.SetOngoingRewardPercent(v)
	return _c
}

// SetNillableOngoingRewardPercent sets the "ongoing_reward_percent" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableOngoingRewardPercent(v *float64) *UserReferralConfigCreate {
	if v != nil {
		_c.SetOngoingRewardPercent(*v)
	}
	return _c
}

// SetOngoingRewardMaxCount sets the "ongoing_reward_max_count" field.
func (_c *UserReferralConfigCreate) SetOngoingRewardMaxCount(v int) *UserReferralConfigCreate {
	_c.mutation.SetOngoingRewardMaxCount(v)
	return _c
}

// SetNillableOngoingRewardMaxCount sets the "ongoing_reward_max_count" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableOngoingRewardMaxCount(v *int) *UserReferralConfigCreate {
	if v != nil {
		_c.SetOngoingRewardMaxCount(*v)
	}
	return _c
}

// SetOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field.
func (_c *UserReferralConfigCreate) SetOngoingRewardDurationDays(v int) *UserReferralConfigCreate {
	_c.mutation.SetOngoingRewardDurationDays(v)
	return _c
}

// SetNillableOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableOngoingRewardDurationDays(v *int) *UserReferralConfigCreate {
	if v != nil {
		_c.SetOngoingRewardDurationDays(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserReferralConfigCreate) SetNotes(v string) *UserReferralConfigCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableNotes(v *string) *UserReferralConfigCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserReferralConfigCreate) SetCreatedAt(v time.Time) *UserReferralConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableCreatedAt(v *time.Time) *UserReferralConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserReferralConfigCreate) SetUpdatedAt(v time.Time) *UserReferralConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserReferralConfigCreate) SetNillableUpdatedAt(v *time.Time) *UserReferralConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserReferralConfigMutation object of the builder.
func (_c *UserReferralConfigCreate) Mutation() *UserReferralConfigMutation {
	return _c.mutation
}

// Save creates the UserReferralConfig in the database.
func (_c *UserReferralConfigCreate) Save(ctx context.Context) (*UserReferralConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserReferralConfigCreate) SaveX(ctx context.Context) *UserReferralConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserReferralConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserReferralConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserReferralConfigCreate) defaults() {
	if _, ok := _c.mutation.Notes(); !ok {
		v := userreferralconfig.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userreferralconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userreferralconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserReferralConfigCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserReferralConfig.user_id"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "UserReferralConfig.notes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserReferralConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserReferralConfig.updated_at"`)}
	}
	return nil
}

func (_c *UserReferralConfigCreate) sqlSave(ctx context.Context) (*UserReferralConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserReferralConfigCreate) createSpec() (*UserReferralConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &UserReferralConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userreferralconfig.Table, sqlgraph.NewFieldSpec(userreferralconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userreferralconfig.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InviteeRewardAmount(); ok {
		_spec.SetField(userreferralconfig.FieldInviteeRewardAmount, field.TypeFloat64, value)
		_node.InviteeRewardAmount = &value
	}
	if value, ok := _c.mutation.InviterRewardAmount(); ok {
		_spec.SetField(userreferralconfig.FieldInviterRewardAmount, field.TypeFloat64, value)
		_node.InviterRewardAmount = &value
	}
	if value, ok := _c.mutation.MaxInvites(); ok {
		_spec.SetField(userreferralconfig.FieldMaxInvites, field.TypeInt, value)
		_node.MaxInvites = &value
	}
	if value, ok := _c.mutation.RewardExpiryDays(); ok {
		_spec.SetField(userreferralconfig.FieldRewardExpiryDays, field.TypeInt, value)
		_node.RewardExpiryDays = &value
	}
	if value, ok := _c.mutation.OngoingRewardEnabled(); ok {
		_spec.SetField(userreferralconfig.FieldOngoingRewardEnabled, field.TypeBool, value)
		_node.OngoingRewardEnabled = &value
	}
	if value, ok := _c.mutation.OngoingRewardAmount(); ok {
		_spec.SetField(userreferralconfig.FieldOngoingRewardAmount, field.TypeFloat64, value)
		_node.OngoingRewardAmount = &value
	}
	if value, ok := _c.mutation.OngoingRewardPercent(); ok {
		_spec.SetField(userreferralconfig.FieldOngoingRewardPercent, field.TypeFloat64, value)
		_node.OngoingRewardPercent = &value
	}
	if value, ok := _c.mutation.OngoingRewardMaxCount(); ok {
		_spec.SetField(userreferralconfig.FieldOngoingRewardMaxCount, field.TypeInt, value)
		_node.OngoingRewardMaxCount = &value
	}
	if value, ok := _c.mutation.OngoingRewardDurationDays(); ok {
		_spec.SetField(userreferralconfig.FieldOngoingRewardDurationDays, field.TypeInt, value)
		_node.OngoingRewardDurationDays = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(userreferralconfig.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userreferralconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userreferralconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserReferralConfig.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserReferralConfigUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserReferralConfigCreate) OnConflict(opts ...sql.ConflictOption) *UserReferralConfigUpsertOne {
	_c.conflict = opts
	return &UserReferralConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserReferralConfigCreate) OnConflictColumns(columns ...string) *UserReferralConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserReferralConfigUpsertOne{
		create: _c,
	}
}

type (
	// UserReferralConfigUpsertOne is the builder for "upsert"-ing
	//  one UserReferralConfig node.
	UserReferralConfigUpsertOne struct {
		create *UserReferralConfigCreate
	}

	// UserReferralConfigUpsert is the "OnConflict" setter.
	UserReferralConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserReferralConfigUpsert) SetUserID(v int64) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateUserID() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserReferralConfigUpsert) AddUserID(v int64) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldUserID, v)
	return u
}

// SetInviteeRewardAmount sets the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsert) SetInviteeRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldInviteeRewardAmount, v)
	return u
}

// UpdateInviteeRewardAmount sets the "invitee_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateInviteeRewardAmount() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldInviteeRewardAmount)
	return u
}

// AddInviteeRewardAmount adds v to the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsert) AddInviteeRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldInviteeRewardAmount, v)
	return u
}

// ClearInviteeRewardAmount clears the value of the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsert) ClearInviteeRewardAmount() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldInviteeRewardAmount)
	return u
}

// SetInviterRewardAmount sets the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsert) SetInviterRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldInviterRewardAmount, v)
	return u
}

// UpdateInviterRewardAmount sets the "inviter_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateInviterRewardAmount() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldInviterRewardAmount)
	return u
}

// AddInviterRewardAmount adds v to the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsert) AddInviterRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldInviterRewardAmount, v)
	return u
}

// ClearInviterRewardAmount clears the value of the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsert) ClearInviterRewardAmount() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldInviterRewardAmount)
	return u
}

// SetMaxInvites sets the "max_invites" field.
func (u *UserReferralConfigUpsert) SetMaxInvites(v int) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldMaxInvites, v)
	return u
}

// UpdateMaxInvites sets the "max_invites" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateMaxInvites() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldMaxInvites)
	return u
}

// AddMaxInvites adds v to the "max_invites" field.
func (u *UserReferralConfigUpsert) AddMaxInvites(v int) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldMaxInvites, v)
	return u
}

// ClearMaxInvites clears the value of the "max_invites" field.
func (u *UserReferralConfigUpsert) ClearMaxInvites() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldMaxInvites)
	return u
}

// SetRewardExpiryDays sets the "reward_expiry_days" field.
func (u *UserReferralConfigUpsert) SetRewardExpiryDays(v int) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldRewardExpiryDays, v)
	return u
}

// UpdateRewardExpiryDays sets the "reward_expiry_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateRewardExpiryDays() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldRewardExpiryDays)
	return u
}

// AddRewardExpiryDays adds v to the "reward_expiry_days" field.
func (u *UserReferralConfigUpsert) AddRewardExpiryDays(v int) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldRewardExpiryDays, v)
	return u
}

// ClearRewardExpiryDays clears the value of the "reward_expiry_days" field.
func (u *UserReferralConfigUpsert) ClearRewardExpiryDays() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldRewardExpiryDays)
	return u
}

// SetOngoingRewardEnabled sets the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsert) SetOngoingRewardEnabled(v bool) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldOngoingRewardEnabled, v)
	return u
}

// UpdateOngoingRewardEnabled sets the "ongoing_reward_enabled" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateOngoingRewardEnabled() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldOngoingRewardEnabled)
	return u
}

// ClearOngoingRewardEnabled clears the value of the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsert) ClearOngoingRewardEnabled() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldOngoingRewardEnabled)
	return u
}

// SetOngoingRewardAmount sets the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsert) SetOngoingRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldOngoingRewardAmount, v)
	return u
}

// UpdateOngoingRewardAmount sets the "ongoing_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateOngoingRewardAmount() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldOngoingRewardAmount)
	return u
}

// AddOngoingRewardAmount adds v to the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsert) AddOngoingRewardAmount(v float64) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldOngoingRewardAmount, v)
	return u
}

// ClearOngoingRewardAmount clears the value of the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsert) ClearOngoingRewardAmount() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldOngoingRewardAmount)
	return u
}

// SetOngoingRewardPercent sets the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsert) SetOngoingRewardPercent(v float64) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldOngoingRewardPercent, v)
	return u
}

// UpdateOngoingRewardPercent sets the "ongoing_reward_percent" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateOngoingRewardPercent() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldOngoingRewardPercent)
	return u
}

// AddOngoingRewardPercent adds v to the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsert) AddOngoingRewardPercent(v float64) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldOngoingRewardPercent, v)
	return u
}

// ClearOngoingRewardPercent clears the value of the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsert) ClearOngoingRewardPercent() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldOngoingRewardPercent)
	return u
}

// SetOngoingRewardMaxCount sets the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsert) SetOngoingRewardMaxCount(v int) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldOngoingRewardMaxCount, v)
	return u
}

// UpdateOngoingRewardMaxCount sets the "ongoing_reward_max_count" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateOngoingRewardMaxCount() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldOngoingRewardMaxCount)
	return u
}

// AddOngoingRewardMaxCount adds v to the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsert) AddOngoingRewardMaxCount(v int) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldOngoingRewardMaxCount, v)
	return u
}

// ClearOngoingRewardMaxCount clears the value of the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsert) ClearOngoingRewardMaxCount() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldOngoingRewardMaxCount)
	return u
}

// SetOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsert) SetOngoingRewardDurationDays(v int) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldOngoingRewardDurationDays, v)
	return u
}

// UpdateOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateOngoingRewardDurationDays() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldOngoingRewardDurationDays)
	return u
}

// AddOngoingRewardDurationDays adds v to the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsert) AddOngoingRewardDurationDays(v int) *UserReferralConfigUpsert {
	u.Add(userreferralconfig.FieldOngoingRewardDurationDays, v)
	return u
}

// ClearOngoingRewardDurationDays clears the value of the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsert) ClearOngoingRewardDurationDays() *UserReferralConfigUpsert {
	u.SetNull(userreferralconfig.FieldOngoingRewardDurationDays)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserReferralConfigUpsert) SetNotes(v string) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateNotes() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserReferralConfigUpsert) SetUpdatedAt(v time.Time) *UserReferralConfigUpsert {
	u.Set(userreferralconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserReferralConfigUpsert) UpdateUpdatedAt() *UserReferralConfigUpsert {
	u.SetExcluded(userreferralconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserReferralConfigUpsertOne) UpdateNewValues() *UserReferralConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userreferralconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserReferralConfigUpsertOne) Ignore() *UserReferralConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserReferralConfigUpsertOne) DoNothing() *UserReferralConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserReferralConfigCreate.OnConflict
// documentation for more info.
func (u *UserReferralConfigUpsertOne) Update(set func(*UserReferralConfigUpsert)) *UserReferralConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserReferralConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserReferralConfigUpsertOne) SetUserID(v int64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserReferralConfigUpsertOne) AddUserID(v int64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateUserID() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetInviteeRewardAmount sets the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertOne) SetInviteeRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetInviteeRewardAmount(v)
	})
}

// AddInviteeRewardAmount adds v to the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertOne) AddInviteeRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddInviteeRewardAmount(v)
	})
}

// UpdateInviteeRewardAmount sets the "invitee_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateInviteeRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateInviteeRewardAmount()
	})
}

// ClearInviteeRewardAmount clears the value of the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertOne) ClearInviteeRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearInviteeRewardAmount()
	})
}

// SetInviterRewardAmount sets the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertOne) SetInviterRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetInviterRewardAmount(v)
	})
}

// AddInviterRewardAmount adds v to the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertOne) AddInviterRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddInviterRewardAmount(v)
	})
}

// UpdateInviterRewardAmount sets the "inviter_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateInviterRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateInviterRewardAmount()
	})
}

// ClearInviterRewardAmount clears the value of the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertOne) ClearInviterRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearInviterRewardAmount()
	})
}

// SetMaxInvites sets the "max_invites" field.
func (u *UserReferralConfigUpsertOne) SetMaxInvites(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetMaxInvites(v)
	})
}

// AddMaxInvites adds v to the "max_invites" field.
func (u *UserReferralConfigUpsertOne) AddMaxInvites(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddMaxInvites(v)
	})
}

// UpdateMaxInvites sets the "max_invites" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateMaxInvites() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateMaxInvites()
	})
}

// ClearMaxInvites clears the value of the "max_invites" field.
func (u *UserReferralConfigUpsertOne) ClearMaxInvites() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearMaxInvites()
	})
}

// SetRewardExpiryDays sets the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertOne) SetRewardExpiryDays(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetRewardExpiryDays(v)
	})
}

// AddRewardExpiryDays adds v to the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertOne) AddRewardExpiryDays(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddRewardExpiryDays(v)
	})
}

// UpdateRewardExpiryDays sets the "reward_expiry_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateRewardExpiryDays() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateRewardExpiryDays()
	})
}

// ClearRewardExpiryDays clears the value of the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertOne) ClearRewardExpiryDays() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearRewardExpiryDays()
	})
}

// SetOngoingRewardEnabled sets the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsertOne) SetOngoingRewardEnabled(v bool) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardEnabled(v)
	})
}

// UpdateOngoingRewardEnabled sets the "ongoing_reward_enabled" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateOngoingRewardEnabled() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardEnabled()
	})
}

// ClearOngoingRewardEnabled clears the value of the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsertOne) ClearOngoingRewardEnabled() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardEnabled()
	})
}

// SetOngoingRewardAmount sets the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertOne) SetOngoingRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardAmount(v)
	})
}

// AddOngoingRewardAmount adds v to the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertOne) AddOngoingRewardAmount(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardAmount(v)
	})
}

// UpdateOngoingRewardAmount sets the "ongoing_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateOngoingRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardAmount()
	})
}

// ClearOngoingRewardAmount clears the value of the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertOne) ClearOngoingRewardAmount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardAmount()
	})
}

// SetOngoingRewardPercent sets the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertOne) SetOngoingRewardPercent(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardPercent(v)
	})
}

// AddOngoingRewardPercent adds v to the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertOne) AddOngoingRewardPercent(v float64) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardPercent(v)
	})
}

// UpdateOngoingRewardPercent sets the "ongoing_reward_percent" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateOngoingRewardPercent() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardPercent()
	})
}

// ClearOngoingRewardPercent clears the value of the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertOne) ClearOngoingRewardPercent() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardPercent()
	})
}

// SetOngoingRewardMaxCount sets the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertOne) SetOngoingRewardMaxCount(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardMaxCount(v)
	})
}

// AddOngoingRewardMaxCount adds v to the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertOne) AddOngoingRewardMaxCount(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardMaxCount(v)
	})
}

// UpdateOngoingRewardMaxCount sets the "ongoing_reward_max_count" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateOngoingRewardMaxCount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardMaxCount()
	})
}

// ClearOngoingRewardMaxCount clears the value of the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertOne) ClearOngoingRewardMaxCount() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardMaxCount()
	})
}

// SetOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertOne) SetOngoingRewardDurationDays(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardDurationDays(v)
	})
}

// AddOngoingRewardDurationDays adds v to the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertOne) AddOngoingRewardDurationDays(v int) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardDurationDays(v)
	})
}

// UpdateOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateOngoingRewardDurationDays() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardDurationDays()
	})
}

// ClearOngoingRewardDurationDays clears the value of the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertOne) ClearOngoingRewardDurationDays() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardDurationDays()
	})
}

// SetNotes sets the "notes" field.
func (u *UserReferralConfigUpsertOne) SetNotes(v string) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateNotes() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserReferralConfigUpsertOne) SetUpdatedAt(v time.Time) *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserReferralConfigUpsertOne) UpdateUpdatedAt() *UserReferralConfigUpsertOne {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserReferralConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserReferralConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserReferralConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserReferralConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserReferralConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserReferralConfigCreateBulk is the builder for creating many UserReferralConfig entities in bulk.
type UserReferralConfigCreateBulk struct {
	config
	err      error
	builders []*UserReferralConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the UserReferralConfig entities in the database.
func (_c *UserReferralConfigCreateBulk) Save(ctx context.Context) ([]*UserReferralConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserReferralConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserReferralConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserReferralConfigCreateBulk) SaveX(ctx context.Context) []*UserReferralConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserReferralConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserReferralConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserReferralConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserReferralConfigUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserReferralConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserReferralConfigUpsertBulk {
	_c.conflict = opts
	return &UserReferralConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserReferralConfigCreateBulk) OnConflictColumns(columns ...string) *UserReferralConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserReferralConfigUpsertBulk{
		create: _c,
	}
}

// UserReferralConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of UserReferralConfig nodes.
type UserReferralConfigUpsertBulk struct {
	create *UserReferralConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserReferralConfigUpsertBulk) UpdateNewValues() *UserReferralConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userreferralconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserReferralConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserReferralConfigUpsertBulk) Ignore() *UserReferralConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserReferralConfigUpsertBulk) DoNothing() *UserReferralConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserReferralConfigCreateBulk.OnConflict
// documentation for more info.
func (u *UserReferralConfigUpsertBulk) Update(set func(*UserReferralConfigUpsert)) *UserReferralConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserReferralConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserReferralConfigUpsertBulk) SetUserID(v int64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserReferralConfigUpsertBulk) AddUserID(v int64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateUserID() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetInviteeRewardAmount sets the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) SetInviteeRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetInviteeRewardAmount(v)
	})
}

// AddInviteeRewardAmount adds v to the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) AddInviteeRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddInviteeRewardAmount(v)
	})
}

// UpdateInviteeRewardAmount sets the "invitee_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateInviteeRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateInviteeRewardAmount()
	})
}

// ClearInviteeRewardAmount clears the value of the "invitee_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) ClearInviteeRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearInviteeRewardAmount()
	})
}

// SetInviterRewardAmount sets the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) SetInviterRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetInviterRewardAmount(v)
	})
}

// AddInviterRewardAmount adds v to the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) AddInviterRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddInviterRewardAmount(v)
	})
}

// UpdateInviterRewardAmount sets the "inviter_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateInviterRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateInviterRewardAmount()
	})
}

// ClearInviterRewardAmount clears the value of the "inviter_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) ClearInviterRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearInviterRewardAmount()
	})
}

// SetMaxInvites sets the "max_invites" field.
func (u *UserReferralConfigUpsertBulk) SetMaxInvites(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetMaxInvites(v)
	})
}

// AddMaxInvites adds v to the "max_invites" field.
func (u *UserReferralConfigUpsertBulk) AddMaxInvites(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddMaxInvites(v)
	})
}

// UpdateMaxInvites sets the "max_invites" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateMaxInvites() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateMaxInvites()
	})
}

// ClearMaxInvites clears the value of the "max_invites" field.
func (u *UserReferralConfigUpsertBulk) ClearMaxInvites() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearMaxInvites()
	})
}

// SetRewardExpiryDays sets the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertBulk) SetRewardExpiryDays(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetRewardExpiryDays(v)
	})
}

// AddRewardExpiryDays adds v to the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertBulk) AddRewardExpiryDays(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddRewardExpiryDays(v)
	})
}

// UpdateRewardExpiryDays sets the "reward_expiry_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateRewardExpiryDays() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateRewardExpiryDays()
	})
}

// ClearRewardExpiryDays clears the value of the "reward_expiry_days" field.
func (u *UserReferralConfigUpsertBulk) ClearRewardExpiryDays() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearRewardExpiryDays()
	})
}

// SetOngoingRewardEnabled sets the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsertBulk) SetOngoingRewardEnabled(v bool) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardEnabled(v)
	})
}

// UpdateOngoingRewardEnabled sets the "ongoing_reward_enabled" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateOngoingRewardEnabled() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardEnabled()
	})
}

// ClearOngoingRewardEnabled clears the value of the "ongoing_reward_enabled" field.
func (u *UserReferralConfigUpsertBulk) ClearOngoingRewardEnabled() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardEnabled()
	})
}

// SetOngoingRewardAmount sets the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) SetOngoingRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardAmount(v)
	})
}

// AddOngoingRewardAmount adds v to the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) AddOngoingRewardAmount(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardAmount(v)
	})
}

// UpdateOngoingRewardAmount sets the "ongoing_reward_amount" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateOngoingRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardAmount()
	})
}

// ClearOngoingRewardAmount clears the value of the "ongoing_reward_amount" field.
func (u *UserReferralConfigUpsertBulk) ClearOngoingRewardAmount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardAmount()
	})
}

// SetOngoingRewardPercent sets the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertBulk) SetOngoingRewardPercent(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardPercent(v)
	})
}

// AddOngoingRewardPercent adds v to the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertBulk) AddOngoingRewardPercent(v float64) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardPercent(v)
	})
}

// UpdateOngoingRewardPercent sets the "ongoing_reward_percent" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateOngoingRewardPercent() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardPercent()
	})
}

// ClearOngoingRewardPercent clears the value of the "ongoing_reward_percent" field.
func (u *UserReferralConfigUpsertBulk) ClearOngoingRewardPercent() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardPercent()
	})
}

// SetOngoingRewardMaxCount sets the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertBulk) SetOngoingRewardMaxCount(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardMaxCount(v)
	})
}

// AddOngoingRewardMaxCount adds v to the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertBulk) AddOngoingRewardMaxCount(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardMaxCount(v)
	})
}

// UpdateOngoingRewardMaxCount sets the "ongoing_reward_max_count" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateOngoingRewardMaxCount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardMaxCount()
	})
}

// ClearOngoingRewardMaxCount clears the value of the "ongoing_reward_max_count" field.
func (u *UserReferralConfigUpsertBulk) ClearOngoingRewardMaxCount() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardMaxCount()
	})
}

// SetOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertBulk) SetOngoingRewardDurationDays(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetOngoingRewardDurationDays(v)
	})
}

// AddOngoingRewardDurationDays adds v to the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertBulk) AddOngoingRewardDurationDays(v int) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.AddOngoingRewardDurationDays(v)
	})
}

// UpdateOngoingRewardDurationDays sets the "ongoing_reward_duration_days" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateOngoingRewardDurationDays() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateOngoingRewardDurationDays()
	})
}

// ClearOngoingRewardDurationDays clears the value of the "ongoing_reward_duration_days" field.
func (u *UserReferralConfigUpsertBulk) ClearOngoingRewardDurationDays() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.ClearOngoingRewardDurationDays()
	})
}

// SetNotes sets the "notes" field.
func (u *UserReferralConfigUpsertBulk) SetNotes(v string) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateNotes() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserReferralConfigUpsertBulk) SetUpdatedAt(v time.Time) *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserReferralConfigUpsertBulk) UpdateUpdatedAt() *UserReferralConfigUpsertBulk {
	return u.Update(func(s *UserReferralConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserReferralConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserReferralConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserReferralConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserReferralConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
