// Code generated by ent, DO NOT EDIT.

package salescommissiontier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldID, id))
}

// SalesUserID applies equality check predicate on the "sales_user_id" field. It's identical to SalesUserIDEQ.
func SalesUserID(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldSalesUserID, v))
}

// MonthSalesFromCny applies equality check predicate on the "month_sales_from_cny" field. It's identical to MonthSalesFromCnyEQ.
func MonthSalesFromCny(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldMonthSalesFromCny, v))
}

// MonthSalesToCny applies equality check predicate on the "month_sales_to_cny" field. It's identical to MonthSalesToCnyEQ.
func MonthSalesToCny(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldMonthSalesToCny, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldCommissionRate, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// SalesUserIDEQ applies the EQ predicate on the "sales_user_id" field.
func SalesUserIDEQ(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldSalesUserID, v))
}

// SalesUserIDNEQ applies the NEQ predicate on the "sales_user_id" field.
func SalesUserIDNEQ(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldSalesUserID, v))
}

// SalesUserIDIn applies the In predicate on the "sales_user_id" field.
func SalesUserIDIn(vs ...int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldSalesUserID, vs...))
}

// SalesUserIDNotIn applies the NotIn predicate on the "sales_user_id" field.
func SalesUserIDNotIn(vs ...int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldSalesUserID, vs...))
}

// SalesUserIDGT applies the GT predicate on the "sales_user_id" field.
func SalesUserIDGT(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldSalesUserID, v))
}

// SalesUserIDGTE applies the GTE predicate on the "sales_user_id" field.
func SalesUserIDGTE(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldSalesUserID, v))
}

// SalesUserIDLT applies the LT predicate on the "sales_user_id" field.
func SalesUserIDLT(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldSalesUserID, v))
}

// SalesUserIDLTE applies the LTE predicate on the "sales_user_id" field.
func SalesUserIDLTE(v int64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldSalesUserID, v))
}

// MonthSalesFromCnyEQ applies the EQ predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldMonthSalesFromCny, v))
}

// MonthSalesFromCnyNEQ applies the NEQ predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyNEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldMonthSalesFromCny, v))
}

// MonthSalesFromCnyIn applies the In predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldMonthSalesFromCny, vs...))
}

// MonthSalesFromCnyNotIn applies the NotIn predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyNotIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldMonthSalesFromCny, vs...))
}

// MonthSalesFromCnyGT applies the GT predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyGT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldMonthSalesFromCny, v))
}

// MonthSalesFromCnyGTE applies the GTE predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyGTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldMonthSalesFromCny, v))
}

// MonthSalesFromCnyLT applies the LT predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyLT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldMonthSalesFromCny, v))
}

// MonthSalesFromCnyLTE applies the LTE predicate on the "month_sales_from_cny" field.
func MonthSalesFromCnyLTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldMonthSalesFromCny, v))
}

// MonthSalesToCnyEQ applies the EQ predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyNEQ applies the NEQ predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyNEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyIn applies the In predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldMonthSalesToCny, vs...))
}

// MonthSalesToCnyNotIn applies the NotIn predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyNotIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldMonthSalesToCny, vs...))
}

// MonthSalesToCnyGT applies the GT predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyGT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyGTE applies the GTE predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyGTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyLT applies the LT predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyLT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyLTE applies the LTE predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyLTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldMonthSalesToCny, v))
}

// MonthSalesToCnyIsNil applies the IsNil predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyIsNil() predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIsNull(FieldMonthSalesToCny))
}

// MonthSalesToCnyNotNil applies the NotNil predicate on the "month_sales_to_cny" field.
func MonthSalesToCnyNotNil() predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotNull(FieldMonthSalesToCny))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldCommissionRate, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SalesCommissionTier) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SalesCommissionTier) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SalesCommissionTier) predicate.SalesCommissionTier {
	return predicate.SalesCommissionTier(sql.NotPredicates(p))
}
