// Code generated by ent, DO NOT EDIT.

package promotionplanrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the promotionplanrule type in the database.
	Label = "promotion_plan_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPromotionID holds the string denoting the promotion_id field in the database.
	FieldPromotionID = "promotion_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldDiscountMode holds the string denoting the discount_mode field in the database.
	FieldDiscountMode = "discount_mode"
	// FieldDiscountRate holds the string denoting the discount_rate field in the database.
	FieldDiscountRate = "discount_rate"
	// FieldDiscountAmount holds the string denoting the discount_amount field in the database.
	FieldDiscountAmount = "discount_amount"
	// FieldMinPriceFloor holds the string denoting the min_price_floor field in the database.
	FieldMinPriceFloor = "min_price_floor"
	// FieldMaxUsesPerUser holds the string denoting the max_uses_per_user field in the database.
	FieldMaxUsesPerUser = "max_uses_per_user"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePromotion holds the string denoting the promotion edge name in mutations.
	EdgePromotion = "promotion"
	// Table holds the table name of the promotionplanrule in the database.
	Table = "promotion_plan_rules"
	// PromotionTable is the table that holds the promotion relation/edge.
	PromotionTable = "promotion_plan_rules"
	// PromotionInverseTable is the table name for the Promotion entity.
	// It exists in this package in order to avoid circular dependency with the "promotion" package.
	PromotionInverseTable = "promotions"
	// PromotionColumn is the table column denoting the promotion relation/edge.
	PromotionColumn = "promotion_id"
)

// Columns holds all SQL columns for promotionplanrule fields.
var Columns = []string{
	FieldID,
	FieldPromotionID,
	FieldPlanID,
	FieldDiscountMode,
	FieldDiscountRate,
	FieldDiscountAmount,
	FieldMinPriceFloor,
	FieldMaxUsesPerUser,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DiscountModeValidator is a validator for the "discount_mode" field. It is called by the builders before save.
	DiscountModeValidator func(string) error
	// DefaultMinPriceFloor holds the default value on creation for the "min_price_floor" field.
	DefaultMinPriceFloor float64
	// DefaultMaxUsesPerUser holds the default value on creation for the "max_uses_per_user" field.
	DefaultMaxUsesPerUser int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PromotionPlanRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPromotionID orders the results by the promotion_id field.
func ByPromotionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromotionID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByDiscountMode orders the results by the discount_mode field.
func ByDiscountMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountMode, opts...).ToFunc()
}

// ByDiscountRate orders the results by the discount_rate field.
func ByDiscountRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountRate, opts...).ToFunc()
}

// ByDiscountAmount orders the results by the discount_amount field.
func ByDiscountAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountAmount, opts...).ToFunc()
}

// ByMinPriceFloor orders the results by the min_price_floor field.
func ByMinPriceFloor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinPriceFloor, opts...).ToFunc()
}

// ByMaxUsesPerUser orders the results by the max_uses_per_user field.
func ByMaxUsesPerUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUsesPerUser, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPromotionField orders the results by promotion field.
func ByPromotionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromotionStep(), sql.OrderByField(field, opts...))
	}
}
func newPromotionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromotionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PromotionTable, PromotionColumn),
	)
}
