// Code generated by ent, DO NOT EDIT.

package promotion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the promotion type in the database.
	Label = "promotion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPromotionType holds the string denoting the promotion_type field in the database.
	FieldPromotionType = "promotion_type"
	// FieldDiscountMode holds the string denoting the discount_mode field in the database.
	FieldDiscountMode = "discount_mode"
	// FieldRechargeRate holds the string denoting the recharge_rate field in the database.
	FieldRechargeRate = "recharge_rate"
	// FieldRechargeBonusRate holds the string denoting the recharge_bonus_rate field in the database.
	FieldRechargeBonusRate = "recharge_bonus_rate"
	// FieldMaxUsesPerUser holds the string denoting the max_uses_per_user field in the database.
	FieldMaxUsesPerUser = "max_uses_per_user"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlanRules holds the string denoting the plan_rules edge name in mutations.
	EdgePlanRules = "plan_rules"
	// EdgeUsages holds the string denoting the usages edge name in mutations.
	EdgeUsages = "usages"
	// Table holds the table name of the promotion in the database.
	Table = "promotions"
	// PlanRulesTable is the table that holds the plan_rules relation/edge.
	PlanRulesTable = "promotion_plan_rules"
	// PlanRulesInverseTable is the table name for the PromotionPlanRule entity.
	// It exists in this package in order to avoid circular dependency with the "promotionplanrule" package.
	PlanRulesInverseTable = "promotion_plan_rules"
	// PlanRulesColumn is the table column denoting the plan_rules relation/edge.
	PlanRulesColumn = "promotion_id"
	// UsagesTable is the table that holds the usages relation/edge.
	UsagesTable = "promotion_usages"
	// UsagesInverseTable is the table name for the PromotionUsage entity.
	// It exists in this package in order to avoid circular dependency with the "promotionusage" package.
	UsagesInverseTable = "promotion_usages"
	// UsagesColumn is the table column denoting the usages relation/edge.
	UsagesColumn = "promotion_id"
)

// Columns holds all SQL columns for promotion fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldPromotionType,
	FieldDiscountMode,
	FieldRechargeRate,
	FieldRechargeBonusRate,
	FieldMaxUsesPerUser,
	FieldStartsAt,
	FieldEndsAt,
	FieldStatus,
	FieldPriority,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// PromotionTypeValidator is a validator for the "promotion_type" field. It is called by the builders before save.
	PromotionTypeValidator func(string) error
	// DefaultDiscountMode holds the default value on creation for the "discount_mode" field.
	DefaultDiscountMode string
	// DiscountModeValidator is a validator for the "discount_mode" field. It is called by the builders before save.
	DiscountModeValidator func(string) error
	// DefaultMaxUsesPerUser holds the default value on creation for the "max_uses_per_user" field.
	DefaultMaxUsesPerUser int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Promotion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPromotionType orders the results by the promotion_type field.
func ByPromotionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromotionType, opts...).ToFunc()
}

// ByDiscountMode orders the results by the discount_mode field.
func ByDiscountMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountMode, opts...).ToFunc()
}

// ByRechargeRate orders the results by the recharge_rate field.
func ByRechargeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeRate, opts...).ToFunc()
}

// ByRechargeBonusRate orders the results by the recharge_bonus_rate field.
func ByRechargeBonusRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeBonusRate, opts...).ToFunc()
}

// ByMaxUsesPerUser orders the results by the max_uses_per_user field.
func ByMaxUsesPerUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUsesPerUser, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlanRulesCount orders the results by plan_rules count.
func ByPlanRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlanRulesStep(), opts...)
	}
}

// ByPlanRules orders the results by plan_rules terms.
func ByPlanRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsagesCount orders the results by usages count.
func ByUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagesStep(), opts...)
	}
}

// ByUsages orders the results by usages terms.
func ByUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlanRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanRulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlanRulesTable, PlanRulesColumn),
	)
}
func newUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
	)
}
